(function(){
  const root = window.SpinClash;

  function cloneLocale(value){
    if(Array.isArray(value)) return value.map(cloneLocale);
    if(value && typeof value === 'object'){
      const result = {};
      Object.keys(value).forEach(function(key){
        result[key] = cloneLocale(value[key]);
      });
      return result;
    }
    return value;
  }

  const textEn = {
    titleMain:'SPIN CLASH',
    titleSub:'ARENA DUEL',
    titleTagline:'Short, violent spin duels with no dead time and no backend baggage.',
    titleProgressLabel:'PATH STATUS',
    titleGoalLabel:'NEXT TARGET',
    titleQuickBattle:'QUICK BATTLE',
    titleWorkshop:'WORKSHOP',
    settingsTitle:'SETTINGS',
    backButton:'BACK',
    routeFromLabel:'FROM',
    homeRoute:'HOME',
    continuePath:'CONTINUE PATH',
    enterBattle:'CONTINUE PATH',
    loadoutTitle:'SELECT YOUR TOP',
    featuredTopTitle:'SELECTED TOP',
    featuredTraitsTitle:'TRACK TRAITS',
    homeTopTitle:'CURRENT TOP',
    homeTopCountLabel:'UNLOCKED',
    homeTopUnlocked:'UNLOCKED',
    homeTopLocked:'LOCKED',
    homeTopLockedSkill:'Silhouette only. Full ability data unlocks later.',
    homeTopLockedHint:'Unlock this top to reveal its full shape and material finish.',
    homeTopLockedHintRoad:'Clear deeper Championship Path nodes to reveal this top.',
    homeTopLockedHintShop:'Unlock this top from the Workshop once you have enough SCRAP.',
    homeTopLockedHintRoadShop:'Unlock this top on the Path or buy it in the Workshop.',
    homeTopPrev:'<',
    homeTopNext:'>',
    homeTopEmpty:'Choose an unlocked top to preview its strengths.',
    quickBattleSubtitle:'QUICK BATTLE',
    quickArenaTitle:'SELECTED ARENA',
    quickArenaUnlocked:'UNLOCKED',
    quickArenaLocked:'LOCKED',
    quickArenaDescriptions:{
      circle_bowl:'Balanced circular bowl with the cleanest center-control reads.',
      heart_bowl:'Heart bowl that exaggerates angle pressure and edge decisions.',
      hex_bowl:'Hex bowl with harsher rebounds and tighter escape lanes.'
    },
    quickTopTitle:'DEPLOYED TOP',
    quickTopLocked:'LOCKED',
    quickTopReady:'READY',
    quickTopLockedHint:'Locked tops cannot enter quick battle.',
    homeRouteLockedHint:'The previewed top is locked. Switch back to an unlocked top before entering battle routes.',
    quickStartBlockedHint:'You cannot enter battle with a locked top. Return Home and switch to an unlocked top.',
    quickStartBlockedButton:'TOP LOCKED',
    quickStartReadyHint:'Arena selected. Start when ready.',
    quickStartArenaLockedHint:'This arena is locked. Start to unlock it or activate a trial.',
    quickStartArenaUnlockButton:'UNLOCK + START',
    quickStartArenaUnlockHint:'Spend {cost} SCRAP to unlock this arena, then begin immediately.',
    quickStartArenaTrialButton:'WATCH AD TRIAL',
    quickStartArenaTrialHint:'SCRAP is short. Watch an ad to activate a session trial for this arena.',
    challengeSubtitle:'CHAMPIONSHIP PATH',
    arenaOptions:['CIRCLE BOWL','HEART BOWL','HEX BOWL'],
    fightButton:'START MATCH',
    challengeButton:'ENTER PATH',
    roundNext:'Next round starts shortly',
    replay:'PLAY AGAIN',
    nextNode:'NEXT NODE',
    retryNode:'RETRY NODE',
    roadClear:'ROAD CLEAR',
    rematch:'CHANGE TOP',
    rewardDouble:'DOUBLE REWARD',
    rewardClaimed:'DOUBLE CLAIMED',
    rewardContinue:'CONTINUE +AD',
    rewardBusy:'REWARD ALREADY IN PROGRESS.',
    rewardLoading:'AD IS LOADING. TRY AGAIN.',
    rewardUnavailable:'REWARD NOT AVAILABLE RIGHT NOW.',
    rewardDeclined:'NO REWARD WAS GRANTED.',
    rewardError:'REWARD FLOW FAILED.',
    rewardDoubleFail:'DOUBLE REWARD NOT GRANTED.',
    rewardContinueFail:'CONTINUE NOT GRANTED.',
    rewardTrialFail:'TRIAL NOT GRANTED.',
    shareResult:'SHARE RESULT',
    resultBreakdownBase:'BASE',
    resultBreakdownNode:'NODE',
    resultBreakdownFirstClear:'FIRST CLEAR',
    resultBreakdownRank:'RANK BONUS',
    resultNextNodeLabel:'Next',
    resultRetryLabel:'Retry',
    resultRoadLabel:'Road',
    resultArenaLabel:'Arena',
    resultNodeLabel:'Node',
    resultReasonLabel:'Finish',
    resultShareLabel:'Share moment',
    resultRewardLabel:'Reward',
    resultReturnToPath:'RETURN TO PATH',
    resultReturnToQuick:'RETURN TO QUICK',
    resultReturnToHome:'RETURN HOME',
    resultAdjustPath:'ADJUST PATH LOADOUT',
    resultAdjustQuick:'ADJUST QUICK LOADOUT',
    resultAdjustHome:'CHANGE TOP',
    quickMode:'QUICK BATTLE',
    challengeMode:'CHAMPIONSHIP PATH',
    workshopToggle:'OPEN WORKSHOP',
    workshopClose:'CLOSE WORKSHOP',
    workshopTitle:'WORKSHOP RESEARCH',
    workshopHint:'Permanent SCRAP upgrades. Effects apply to every duel.',
    workshopBuy:'UPGRADE',
    workshopMaxed:'MAXED',
    workshopLocked:'MORE SCRAP NEEDED',
    workshopUnlocked:'RESEARCH UPGRADED',
    workshopLevel:'LV',
    workshopCurrent:'ACTIVE',
    workshopNext:'NEXT',
    settingsHint:'Language and audio toggles update immediately and persist to the current local save.',
    settingsLanguageLabel:'LANGUAGE: use the locale buttons above.',
    settingsAudioLabel:'AUDIO',
    settingsMusicOn:'MUSIC: ON',
    settingsMusicOff:'MUSIC: OFF',
    settingsSfxOn:'SFX: ON',
    settingsSfxOff:'SFX: OFF',
    roadRankTitle:'ROAD RANK',
    roadRankLocked:'LOCKED',
    roadRankUnlocked:'UNLOCKED',
    roadRankHint:'Select a higher rank for stronger enemies and better rewards.',
    roadRankRewardLabel:'Reward',
    challengeLocked:'Clear the current node to unlock the next duel.',
    challengeComplete:'Road clear complete. Replay for better rewards.',
    challengeFail:'Challenge failed. Use one continue or retry the node.',
    challengeContinueUsed:'Continue used for this node.',
    unlockArena:'UNLOCKED',
    unlockTop:'TOP UNLOCKED',
    unlockTopReward:'ROAD REWARD UNLOCKED',
    trialArena:'TRIAL ACTIVE',
    lockedArena:'LOCKED',
    lockedTop:'LOCKED',
    playerRole:'YOU',
    enemyRole:'CPU',
    statusReady:'READY',
    statusGuarding:'GUARD',
    statusIntentSkill:'SKILL',
    statusIntentDash:'DASH',
    statusIntentGuard:'GUARD',
    hp:'HP',
    spin:'SPIN',
    burst:'BURST',
    dashName:'DASH',
    dashIcon:'⚡',
    guardName:'GUARD',
    guardIcon:'🛡',
    swapIcon:'⇄',
    swapLabel:'SWAP',
    loadoutHintQuick:'Choose an arena for a one-off duel. Your current top is confirmed from Home.',
    loadoutHintChallenge:'Battle through fixed nodes with modifiers and persistent rewards.',
    storageNoticeSession:'SAVE MODE: SESSION ONLY. PROGRESS MAY NOT SURVIVE A NEW TAB.',
    storageNoticeWindowName:'SAVE MODE: THIS TAB ONLY. PROGRESS MAY NOT SURVIVE A NEW WINDOW.',
    storageNoticeMemory:'SAVE MODE: TEMPORARY ONLY. PROGRESS WILL BE LOST ON RELOAD.',
    shareTitle:'Spin Clash',
    sharePrefix:'Spin Clash result',
    shareMoments:{
      road_clear:'ROAD CLEAR',
      challenge_clear:'CHALLENGE CLEAR',
      ring_out:'RING OUT',
      perfect_win:'PERFECT WIN',
      close_loss:'CLOSE LOSS',
      victory:'VICTORY',
      defeat:'DEFEAT'
    },
    shareTemplates:{
      road_clear:'{title}: cleared the full Challenge Road in {arena} with {top}.',
      challenge_clear:'{title}: cleared Node {node} in {arena} with {top}.',
      ring_out:'{title}: landed a ring-out finish in {arena} with {top}.',
      perfect_win:'{title}: won {scorePlayer}-{scoreEnemy} in {arena} with {top}.',
      close_loss:'{title}: lost {scorePlayer}-{scoreEnemy} in {arena}. Rematch time.',
      victory:'{title}: won in {arena} with {top}.',
      defeat:'{title}: battled in {arena} with {top}.'
    },
    currencyLabel:'SCRAP',
    walletLabel:'BALANCE',
    localeButtons:{
      en:'EN',
      zh:'中文',
      ja:'日本語'
    },
    hintAim:'Drag to aim, then release to launch.',
    hintActive:'SPACE to dash | E to guard | Q to use your burst skill.',
    hintSkillReady:'Q READY',
    roundLabel:'ROUND',
    roundWinPlayer:'YOU WIN!',
    roundWinEnemy:'ENEMY WINS',
    roundWinDraw:'DRAW',
    roundReasonRingOut:'Ring Out',
    roundReasonSpinOut:'Spin Out',
    roundReasonHpBreak:'HP Break',
    roundReasonTimeUp:'Time Up - HP Check',
    fightCallout:'FIGHT!',
    nodeLocked:'Node locked.',
    checkpointLabel:'CHECKPOINT',
    tierBoss:'BOSS',
    tierFinal:'FINAL',
    resumeLabel:'Resume',
    noBonus:'NO BONUS',
    battleIntroQuickStage:'QUICK BATTLE',
    battleIntroNodeLabel:'NODE',
    battleIntroVersus:' VS ',
    skillLabels:{
      'Fly Charge':'Fly Charge',
      'Fortress Pulse':'Fortress Pulse',
      'Phantom':'Phantom'
    },
    skillMessages:{
      player:{
        'Fly Charge':'Fly Charge!',
        'Fortress Pulse':'Fortress Pulse!',
        'Phantom':'Phantom!'
      },
      enemy:{
        'Fly Charge':'Enemy used Fly Charge!',
        'Fortress Pulse':'Enemy used Fortress Pulse!',
        'Phantom':'Enemy used Phantom!'
      }
    },
    messageDash:'DASH!',
    messageGuard:'GUARD!',
    messageBurstOrb:'+55 BURST',
    messageHeavyCollision:'Heavy Collision!',
    messageSuperImpact:'Super Impact!!',
    messagePlayerRingOut:'You were knocked out of the arena!',
    messageEnemyRingOut:'The opponent flew out of the arena!',
    copyShareText:'Copy share text',
    shareCardPlayerTop:'PLAYER TOP',
    shareCardEnemyTop:'ENEMY TOP',
    shareCardChallengeRoad:'CHALLENGE ROAD',
    shareCardNode:'NODE',
    shareCardOpenMatch:'OPEN MATCH',
    shareCardQuickBattle:'QUICK BATTLE',
    shareCardVictory:'VICTORY',
    shareCardDefeat:'DEFEAT',
    cards:[
      {
        icon:'⚔',
        type:'IMPACT',
        stats:'HP 85<br>SPIN 95<br>SPEED 14<br>MASS 1.2',
        skill:'⚔ Fly Charge · Surge straight at the target.',
        pitch:'Hard entry top that turns the first clean angle into momentum.',
        traits:['Front-load damage','Punishes loose launches','Best when you force center contact']
      },
      {
        icon:'🛡',
        type:'ARMOR',
        stats:'HP 120<br>SPIN 75<br>SPEED 10<br>MASS 1.5',
        skill:'🛡 Fortress Pulse · Anchor the lane and blast the rival outward.',
        pitch:'Heavy control pick that stabilizes itself and wins space with a shock pulse.',
        traits:['Strong anti-rush pulse','Best at reclaiming center','Slow to reposition']
      },
      {
        icon:'👾',
        type:'TRICK',
        stats:'HP 70<br>SPIN 100<br>SPEED 16<br>MASS 0.9',
        skill:'👾 Phantom · Speed burst and pressure.',
        pitch:'Angle-hunting top that lives off drift lines and edge pressure.',
        traits:['Fast edge recovery','Sharp burst tempo','Low mistake tolerance']
      },
      {
        icon:'✦',
        type:'BREAKER',
        stats:'HP 78<br>SPIN 98<br>SPEED 15<br>MASS 1.1',
        skill:'✦ Fly Charge · Faster line break with lower stability.',
        pitch:'Aggressive variant that cashes in on direct launch lines immediately.',
        traits:['Explosive opener','Higher chase speed','Falls off if stalled']
      },
      {
        icon:'☄',
        type:'RAIDER',
        stats:'HP 66<br>SPIN 104<br>SPEED 17<br>MASS 0.8',
        skill:'☄ Phantom · Sharper edge hunting and burst tempo.',
        pitch:'Predatory drift variant built for arena abuse and clutch scrambles.',
        traits:['Best on risky walls','Excellent comeback pressure','Lowest durability']
      }
    ]
  };

  const textZh = {
    titleMain:'SPIN CLASH',
    titleSub:'竞技对决',
    titleTagline:'短局、高烈度的陀螺对决，没有拖沓，也没有后端负担。',
    titleProgressLabel:'路径进度',
    titleGoalLabel:'下一目标',
    titleQuickBattle:'快速对战',
    titleWorkshop:'工坊研究',
    settingsTitle:'设置',
    backButton:'返回',
    routeFromLabel:'来源',
    homeRoute:'主页',
    continuePath:'继续征途',
    enterBattle:'继续征途',
    loadoutTitle:'选择陀螺',
    featuredTopTitle:'当前陀螺',
    featuredTraitsTitle:'特性概览',
    homeTopTitle:'当前陀螺',
    homeTopCountLabel:'已解锁',
    homeTopUnlocked:'已解锁',
    homeTopLocked:'未解锁',
    homeTopLockedSkill:'当前仅显示暗影预览，完整能力信息将在解锁后公开。',
    homeTopLockedHint:'解锁后可查看它的完整材质、轮廓与能力说明。',
    homeTopLockedHintRoad:'继续推进冠军之路更深节点后可解锁这只陀螺。',
    homeTopLockedHintShop:'积累足够 SCRAP 后，可在工坊中解锁这只陀螺。',
    homeTopLockedHintRoadShop:'这只陀螺可在冠军之路奖励或工坊购买中解锁。',
    homeTopPrev:'<',
    homeTopNext:'>',
    homeTopEmpty:'切换已解锁陀螺，查看它们的定位与优势。',
    quickBattleSubtitle:'快速对战',
    quickArenaTitle:'当前场地',
    quickArenaUnlocked:'已解锁',
    quickArenaLocked:'未解锁',
    quickArenaDescriptions:{
      circle_bowl:'标准圆形碗场，最容易看清中圈争夺。',
      heart_bowl:'心形碗场会放大角度压迫与边缘决策。',
      hex_bowl:'六角碗场反弹更硬，脱离路线更紧。'
    },
    quickTopTitle:'出战陀螺',
    quickTopLocked:'未解锁',
    quickTopReady:'可出战',
    quickTopLockedHint:'未解锁的陀螺不能进入快速对战。',
    homeRouteLockedHint:'当前预览的陀螺尚未解锁，请先切回已解锁陀螺，再进入对战路线。',
    quickStartBlockedHint:'当前陀螺未解锁，不能出战。请回到主页切换已解锁陀螺。',
    quickStartBlockedButton:'无法出战',
    quickStartReadyHint:'场地已选定，可以直接开始。',
    quickStartArenaLockedHint:'该场地尚未解锁，开始时会尝试解锁或进入试用。',
    quickStartArenaUnlockButton:'解锁并开始',
    quickStartArenaUnlockHint:'消耗 {cost} SCRAP 解锁该场地，并立即开始对战。',
    quickStartArenaTrialButton:'广告试玩',
    quickStartArenaTrialHint:'当前 SCRAP 不足，可看广告开启该场地的本次会话试用。',
    challengeSubtitle:'冠军之路',
    arenaOptions:['圆形碗场','心形碗场','六角碗场'],
    fightButton:'开始对战',
    challengeButton:'进入征途',
    roundNext:'下一回合即将开始',
    replay:'再来一局',
    nextNode:'下一节点',
    retryNode:'重试节点',
    roadClear:'通关完成',
    rematch:'更换陀螺',
    rewardDouble:'双倍奖励',
    rewardClaimed:'双倍已领取',
    rewardContinue:'继续挑战 +广告',
    rewardBusy:'奖励流程正在进行中。',
    rewardLoading:'广告正在加载，请稍后再试。',
    rewardUnavailable:'当前暂时无法提供奖励。',
    rewardDeclined:'未获得奖励。',
    rewardError:'奖励流程失败。',
    rewardDoubleFail:'未能获得双倍奖励。',
    rewardContinueFail:'未能获得继续挑战。',
    rewardTrialFail:'未能获得试用资格。',
    shareResult:'分享战绩',
    resultBreakdownBase:'基础',
    resultBreakdownNode:'节点',
    resultBreakdownFirstClear:'首通',
    resultBreakdownRank:'段位加成',
    resultNextNodeLabel:'下一步',
    resultRetryLabel:'重试',
    resultRoadLabel:'征途',
    resultArenaLabel:'场地',
    resultNodeLabel:'节点',
    resultReasonLabel:'结束方式',
    resultShareLabel:'分享时刻',
    resultRewardLabel:'奖励',
    resultReturnToPath:'返回冠军之路',
    resultReturnToQuick:'返回快速对战',
    resultReturnToHome:'返回主页',
    resultAdjustPath:'返回冠军之路调整配置',
    resultAdjustQuick:'返回快速对战调整配置',
    resultAdjustHome:'更换陀螺',
    quickMode:'快速对战',
    challengeMode:'冠军之路',
    workshopToggle:'打开工坊',
    workshopClose:'收起工坊',
    workshopTitle:'工坊研究',
    workshopHint:'使用 SCRAP 进行永久研究强化，效果会应用到每一场对决。',
    workshopBuy:'升级',
    workshopMaxed:'已满级',
    workshopLocked:'SCRAP 不足',
    workshopUnlocked:'研究已升级',
    workshopLevel:'LV',
    workshopCurrent:'当前',
    workshopNext:'下一级',
    settingsHint:'语言和音频开关会立即生效，并保存到当前本地存档。',
    settingsLanguageLabel:'语言：使用上方语言按钮切换。',
    settingsAudioLabel:'音频',
    settingsMusicOn:'音乐：开启',
    settingsMusicOff:'音乐：关闭',
    settingsSfxOn:'音效：开启',
    settingsSfxOff:'音效：关闭',
    roadRankTitle:'道路段位',
    roadRankLocked:'未解锁',
    roadRankUnlocked:'已解锁',
    roadRankHint:'提高段位可遭遇更强的敌人，并获得更高奖励。',
    roadRankRewardLabel:'奖励',
    challengeLocked:'先通过当前节点，才能解锁下一场对决。',
    challengeComplete:'冠军之路已通关，可重复挑战以获取更高奖励。',
    challengeFail:'挑战失败。你可以使用一次继续，或重试当前节点。',
    challengeContinueUsed:'本节点已使用继续。',
    unlockArena:'已解锁',
    unlockTop:'陀螺已解锁',
    unlockTopReward:'道路奖励已解锁',
    trialArena:'试用中',
    lockedArena:'未解锁',
    lockedTop:'未解锁',
    playerRole:'你',
    enemyRole:'电脑',
    statusReady:'已就绪',
    statusGuarding:'防御中',
    statusIntentSkill:'蓄技中',
    statusIntentDash:'突进中',
    statusIntentGuard:'起盾中',
    hp:'HP',
    spin:'SPIN',
    burst:'BURST',
    dashName:'冲刺',
    dashIcon:'⚡',
    guardName:'防御',
    guardIcon:'🛡',
    swapIcon:'⇄',
    swapLabel:'切换',
    loadoutHintQuick:'选择场地开始单局对战，当前陀螺由主页决定。',
    loadoutHintChallenge:'沿固定节点连续挑战，在修饰器和持久奖励中一路推进。',
    storageNoticeSession:'保存模式：仅当前会话。重新开标签页后，进度可能不会保留。',
    storageNoticeWindowName:'保存模式：仅当前标签页。打开新窗口后，进度可能不会保留。',
    storageNoticeMemory:'保存模式：临时内存。刷新页面后，进度会丢失。',
    shareTitle:'Spin Clash',
    sharePrefix:'Spin Clash 战绩',
    shareMoments:{
      road_clear:'征途通关',
      challenge_clear:'节点突破',
      ring_out:'击飞出场',
      perfect_win:'完胜',
      close_loss:'惜败',
      victory:'胜利',
      defeat:'落败'
    },
    shareTemplates:{
      road_clear:'{title}：我用 {top} 在 {arena} 打通了整条冠军之路。',
      challenge_clear:'{title}：我用 {top} 在 {arena} 突破了第 {node} 节点。',
      ring_out:'{title}：我用 {top} 在 {arena} 完成了击飞出场。',
      perfect_win:'{title}：我用 {top} 在 {arena} 以 {scorePlayer}-{scoreEnemy} 完胜。',
      close_loss:'{title}：我在 {arena} 以 {scorePlayer}-{scoreEnemy} 惜败，准备复仇。',
      victory:'{title}：我用 {top} 在 {arena} 赢下了对战。',
      defeat:'{title}：我在 {arena} 驾驭 {top} 打完了一场硬仗。'
    },
    currencyLabel:'SCRAP',
    walletLabel:'余额',
    localeButtons:{
      en:'EN',
      zh:'中文',
      ja:'日本語'
    },
    hintAim:'拖拽瞄准，松手发射。',
    hintActive:'按 SPACE 冲刺 | 按 E 防御 | 按 Q 释放爆发技能。',
    hintSkillReady:'Q 已就绪',
    roundLabel:'回合',
    roundWinPlayer:'你获胜！',
    roundWinEnemy:'对手获胜',
    roundWinDraw:'平局',
    roundReasonRingOut:'击飞出场',
    roundReasonSpinOut:'转力耗尽',
    roundReasonHpBreak:'耐久崩解',
    roundReasonTimeUp:'时间到 - 按耐久判定',
    fightCallout:'开战！',
    nodeLocked:'节点尚未解锁。',
    checkpointLabel:'检查点',
    tierBoss:'首领',
    tierFinal:'决赛',
    resumeLabel:'续接自',
    noBonus:'暂无加成',
    battleIntroQuickStage:'快速对战',
    battleIntroNodeLabel:'节点',
    battleIntroVersus:' VS ',
    skillLabels:{
      'Fly Charge':'飞冲',
      'Fortress Pulse':'堡垒脉冲',
      'Phantom':'幻袭'
    },
    skillMessages:{
      player:{
        'Fly Charge':'飞冲！',
        'Fortress Pulse':'堡垒脉冲！',
        'Phantom':'幻袭！'
      },
      enemy:{
        'Fly Charge':'敌方使出了飞冲！',
        'Fortress Pulse':'敌方使出了堡垒脉冲！',
        'Phantom':'敌方使出了幻袭！'
      }
    },
    messageDash:'冲刺！',
    messageGuard:'防御！',
    messageBurstOrb:'+55 BURST',
    messageHeavyCollision:'重击碰撞！',
    messageSuperImpact:'超强冲击！',
    messagePlayerRingOut:'你被撞出了场地！',
    messageEnemyRingOut:'对手被撞飞出场！',
    copyShareText:'复制分享文本',
    shareCardPlayerTop:'玩家陀螺',
    shareCardEnemyTop:'敌方陀螺',
    shareCardChallengeRoad:'冠军之路',
    shareCardNode:'节点',
    shareCardOpenMatch:'自由对战',
    shareCardQuickBattle:'快速对战',
    shareCardVictory:'胜利',
    shareCardDefeat:'落败',
    cards:[
      {
        icon:'⚔',
        type:'冲击型',
        stats:'HP 85<br>SPIN 95<br>SPEED 14<br>MASS 1.2',
        skill:'⚔ 飞冲 · 沿直线猛扑目标。',
        pitch:'强势先手型陀螺，只要抓到第一道干净角度，就能顺势滚起节奏。',
        traits:['前段伤害高','擅长惩罚松散发射','逼住中圈时最强']
      },
      {
        icon:'🛡',
        type:'装甲型',
        stats:'HP 120<br>SPIN 75<br>SPEED 10<br>MASS 1.5',
        skill:'🛡 堡垒脉冲 · 定住身位并把对手向外震开。',
        pitch:'重型控场选择，靠脉冲震退夺回空间并稳住中圈。',
        traits:['反突进能力强','最擅长回收中圈','重新定位偏慢']
      },
      {
        icon:'👾',
        type:'诡步型',
        stats:'HP 70<br>SPIN 100<br>SPEED 16<br>MASS 0.9',
        skill:'👾 幻袭 · 提速切入并持续施压。',
        pitch:'依赖角度和漂移线生存的猎手型陀螺，最擅长边缘撕扯。',
        traits:['边线回收快','爆发节奏锋利','容错最低']
      },
      {
        icon:'✦',
        type:'破阵型',
        stats:'HP 78<br>SPIN 98<br>SPEED 15<br>MASS 1.1',
        skill:'✦ 飞冲 · 更快破线，但稳定性更低。',
        pitch:'更激进的冲击变体，一旦走到正面发射线就会立刻兑现伤害。',
        traits:['开局爆发更猛','追击速度更高','被拖慢后衰减明显']
      },
      {
        icon:'☄',
        type:'掠袭型',
        stats:'HP 66<br>SPIN 104<br>SPEED 17<br>MASS 0.8',
        skill:'☄ 幻袭 · 更锐利的边线猎杀与爆发节奏。',
        pitch:'为风险边墙而生的漂移掠食者，残局反扑尤其凶狠。',
        traits:['危险墙面表现最佳','残局压迫力极强','耐久最低']
      }
    ]
  };

  const textJa = {
    titleMain:'SPIN CLASH',
    titleSub:'アリーナ決戦',
    titleTagline:'短期決戦の高密度スピンデュエル。無駄な待ち時間も、サーバー依存もない。',
    titleProgressLabel:'進行状況',
    titleGoalLabel:'次の目標',
    titleQuickBattle:'クイックバトル',
    titleWorkshop:'ワークショップ',
    settingsTitle:'設定',
    backButton:'戻る',
    routeFromLabel:'遷移元',
    homeRoute:'ホーム',
    continuePath:'ロード再開',
    enterBattle:'ロード再開',
    loadoutTitle:'トップを選択',
    featuredTopTitle:'選択中のトップ',
    featuredTraitsTitle:'特性メモ',
    homeTopTitle:'現在のトップ',
    homeTopCountLabel:'解放済み',
    homeTopUnlocked:'解放済み',
    homeTopLocked:'未解放',
    homeTopLockedSkill:'現在はシルエットのみ。能力詳細は解放後に表示される。',
    homeTopLockedHint:'解放すると素材感、輪郭、能力説明の全体が見えるようになる。',
    homeTopLockedHintRoad:'チャンピオンロードをさらに進めるとこのトップを解放できる。',
    homeTopLockedHintShop:'十分な SCRAP があればワークショップでこのトップを解放できる。',
    homeTopLockedHintRoadShop:'このトップはロード報酬またはワークショップ購入で解放できる。',
    homeTopPrev:'<',
    homeTopNext:'>',
    homeTopEmpty:'解放済みトップを切り替えて強みを確認する。',
    quickBattleSubtitle:'クイックバトル',
    quickArenaTitle:'現在のアリーナ',
    quickArenaUnlocked:'解放済み',
    quickArenaLocked:'未解放',
    quickArenaDescriptions:{
      circle_bowl:'中央制圧の読みが最も素直に出る標準ボウル。',
      heart_bowl:'角度圧と外周判断を強く問うハートボウル。',
      hex_bowl:'反射が硬く、逃げ道が狭いヘックスボウル。'
    },
    quickTopTitle:'出撃トップ',
    quickTopLocked:'未解放',
    quickTopReady:'出撃可能',
    quickTopLockedHint:'未解放のトップではクイックバトルに入れない。',
    homeRouteLockedHint:'現在プレビュー中のトップは未解放。解放済みトップへ戻してから対戦ルートへ入る必要がある。',
    quickStartBlockedHint:'現在のトップは未解放。ホームに戻って解放済みトップへ切り替える必要がある。',
    quickStartBlockedButton:'出撃不可',
    quickStartReadyHint:'アリーナ選択完了。準備ができたら開始。',
    quickStartArenaLockedHint:'このアリーナは未解放。開始時に解放またはトライアルを試みる。',
    quickStartArenaUnlockButton:'解放して開始',
    quickStartArenaUnlockHint:'{cost} SCRAP を使ってこのアリーナを解放し、そのまま対戦を始める。',
    quickStartArenaTrialButton:'広告でトライアル',
    quickStartArenaTrialHint:'SCRAP が不足しているため、広告視聴でこのアリーナのセッショントライアルを開始する。',
    challengeSubtitle:'チャンピオンロード',
    arenaOptions:['サークルボウル','ハートボウル','ヘックスボウル'],
    fightButton:'対戦開始',
    challengeButton:'ロード開始',
    roundNext:'次のラウンドがまもなく始まる',
    replay:'もう一戦',
    nextNode:'次のノード',
    retryNode:'ノード再挑戦',
    roadClear:'ロード制覇',
    rematch:'トップ変更',
    rewardDouble:'報酬2倍',
    rewardClaimed:'2倍獲得済み',
    rewardContinue:'コンティニュー +広告',
    rewardBusy:'報酬処理はすでに進行中。',
    rewardLoading:'広告を読み込み中。少し待ってから再試行してください。',
    rewardUnavailable:'現在は報酬を利用できない。',
    rewardDeclined:'報酬は付与されなかった。',
    rewardError:'報酬フローが失敗した。',
    rewardDoubleFail:'報酬2倍を獲得できなかった。',
    rewardContinueFail:'コンティニューを獲得できなかった。',
    rewardTrialFail:'トライアルを獲得できなかった。',
    shareResult:'結果をシェア',
    resultBreakdownBase:'基本',
    resultBreakdownNode:'ノード',
    resultBreakdownFirstClear:'初回突破',
    resultBreakdownRank:'ランク補正',
    resultNextNodeLabel:'次',
    resultRetryLabel:'再挑戦',
    resultRoadLabel:'ロード',
    resultArenaLabel:'アリーナ',
    resultNodeLabel:'ノード',
    resultReasonLabel:'決着',
    resultShareLabel:'共有モーメント',
    resultRewardLabel:'報酬',
    resultReturnToPath:'ロードへ戻る',
    resultReturnToQuick:'クイックへ戻る',
    resultReturnToHome:'ホームへ戻る',
    resultAdjustPath:'ロードで調整',
    resultAdjustQuick:'クイックで調整',
    resultAdjustHome:'トップ変更',
    quickMode:'クイックバトル',
    challengeMode:'チャンピオンロード',
    workshopToggle:'ワークショップを開く',
    workshopClose:'ワークショップを閉じる',
    workshopTitle:'ワークショップ研究',
    workshopHint:'SCRAP を使って恒久研究を強化。効果はすべての対戦に適用される。',
    workshopBuy:'強化',
    workshopMaxed:'最大',
    workshopLocked:'SCRAP 不足',
    workshopUnlocked:'研究を強化した',
    workshopLevel:'LV',
    workshopCurrent:'現在',
    workshopNext:'次',
    settingsHint:'言語と音声トグルは即時反映され、現在のローカルセーブに保存される。',
    settingsLanguageLabel:'言語: 上のロケールボタンで切り替える。',
    settingsAudioLabel:'音声',
    settingsMusicOn:'音楽: ON',
    settingsMusicOff:'音楽: OFF',
    settingsSfxOn:'効果音: ON',
    settingsSfxOff:'効果音: OFF',
    roadRankTitle:'ロードランク',
    roadRankLocked:'未解放',
    roadRankUnlocked:'解放済み',
    roadRankHint:'高いランクを選ぶほど敵は強くなり、報酬も増える。',
    roadRankRewardLabel:'報酬',
    challengeLocked:'次の対戦を解放するには現在のノードを突破する必要がある。',
    challengeComplete:'ロード制覇済み。繰り返し挑戦して報酬を伸ばせる。',
    challengeFail:'挑戦失敗。1回だけコンティニューするか、ノードを再挑戦できる。',
    challengeContinueUsed:'このノードではコンティニュー済み。',
    unlockArena:'解放',
    unlockTop:'トップ解放',
    unlockTopReward:'ロード報酬を解放',
    trialArena:'トライアル中',
    lockedArena:'未解放',
    lockedTop:'未解放',
    playerRole:'YOU',
    enemyRole:'CPU',
    statusReady:'READY',
    statusGuarding:'GUARD',
    statusIntentSkill:'SKILL',
    statusIntentDash:'DASH',
    statusIntentGuard:'GUARD',
    hp:'HP',
    spin:'SPIN',
    burst:'BURST',
    dashName:'ダッシュ',
    dashIcon:'⚡',
    guardName:'ガード',
    guardIcon:'🛡',
    swapIcon:'⇄',
    swapLabel:'切替',
    loadoutHintQuick:'単発対戦のアリーナを選ぶ。現在のトップはホームで決定される。',
    loadoutHintChallenge:'固定ノードを連戦し、モディファイアと持続報酬で進行を押し上げる。',
    storageNoticeSession:'保存モード：このセッションのみ。新しいタブでは進行が残らない場合がある。',
    storageNoticeWindowName:'保存モード：このタブのみ。新しいウィンドウでは進行が残らない場合がある。',
    storageNoticeMemory:'保存モード：一時メモリのみ。再読み込みで進行は失われる。',
    shareTitle:'Spin Clash',
    sharePrefix:'Spin Clash リザルト',
    shareMoments:{
      road_clear:'ロード制覇',
      challenge_clear:'ノード突破',
      ring_out:'リングアウト',
      perfect_win:'完勝',
      close_loss:'惜敗',
      victory:'勝利',
      defeat:'敗北'
    },
    shareTemplates:{
      road_clear:'{title}：{top} で {arena} を制し、チャンピオンロードを完走した。',
      challenge_clear:'{title}：{top} で {arena} のノード {node} を突破した。',
      ring_out:'{title}：{top} で {arena} のリングアウト勝ちを決めた。',
      perfect_win:'{title}：{top} で {arena} を {scorePlayer}-{scoreEnemy} で完勝した。',
      close_loss:'{title}：{arena} で {scorePlayer}-{scoreEnemy} の惜敗。次は取り返す。',
      victory:'{title}：{top} で {arena} を制した。',
      defeat:'{title}：{top} で {arena} を戦い抜いた。'
    },
    currencyLabel:'SCRAP',
    walletLabel:'残高',
    localeButtons:{
      en:'EN',
      zh:'中文',
      ja:'日本語'
    },
    hintAim:'ドラッグで狙い、離して発射。',
    hintActive:'SPACE でダッシュ | E でガード | Q でバーストスキル。',
    hintSkillReady:'Q 準備完了',
    roundLabel:'ROUND',
    roundWinPlayer:'YOU WIN!',
    roundWinEnemy:'ENEMY WINS',
    roundWinDraw:'DRAW',
    roundReasonRingOut:'リングアウト',
    roundReasonSpinOut:'スピン切れ',
    roundReasonHpBreak:'HP ブレイク',
    roundReasonTimeUp:'タイムアップ - HP 判定',
    fightCallout:'FIGHT!',
    nodeLocked:'ノードはまだ解放されていない。',
    checkpointLabel:'チェックポイント',
    tierBoss:'ボス',
    tierFinal:'最終戦',
    resumeLabel:'再開地点',
    noBonus:'ボーナスなし',
    battleIntroQuickStage:'クイックバトル',
    battleIntroNodeLabel:'NODE',
    battleIntroVersus:' VS ',
    skillLabels:{
      'Fly Charge':'フライチャージ',
      'Fortress Pulse':'フォートレスパルス',
      'Phantom':'ファントム'
    },
    skillMessages:{
      player:{
        'Fly Charge':'フライチャージ！',
        'Fortress Pulse':'フォートレスパルス！',
        'Phantom':'ファントム！'
      },
      enemy:{
        'Fly Charge':'敵がフライチャージを使った！',
        'Fortress Pulse':'敵がフォートレスパルスを使った！',
        'Phantom':'敵がファントムを使った！'
      }
    },
    messageDash:'ダッシュ！',
    messageGuard:'ガード！',
    messageBurstOrb:'+55 BURST',
    messageHeavyCollision:'強烈衝突！',
    messageSuperImpact:'超高衝撃!!',
    messagePlayerRingOut:'場外へ弾き出された！',
    messageEnemyRingOut:'相手が場外へ吹き飛んだ！',
    copyShareText:'共有テキストをコピー',
    shareCardPlayerTop:'PLAYER TOP',
    shareCardEnemyTop:'ENEMY TOP',
    shareCardChallengeRoad:'チャンピオンロード',
    shareCardNode:'NODE',
    shareCardOpenMatch:'オープンマッチ',
    shareCardQuickBattle:'クイックバトル',
    shareCardVictory:'VICTORY',
    shareCardDefeat:'DEFEAT',
    cards:[
      {
        icon:'⚔',
        type:'衝撃型',
        stats:'HP 85<br>SPIN 95<br>SPEED 14<br>MASS 1.2',
        skill:'⚔ フライチャージ · 標的へ一直線に突っ込む。',
        pitch:'最初のきれいな角度をそのまま主導権に変える、強烈な先手型トップ。',
        traits:['序盤火力が高い','甘い発射を咎めやすい','中央接触を押し付けると強い']
      },
      {
        icon:'🛡',
        type:'装甲型',
        stats:'HP 120<br>SPIN 75<br>SPEED 10<br>MASS 1.5',
        skill:'🛡 フォートレスパルス · 位置を固めて相手を外へ弾く。',
        pitch:'重厚な制圧型で、衝撃波によって中央を取り返し続ける。',
        traits:['突進迎撃が強い','中央の奪還が得意','立て直しは遅め']
      },
      {
        icon:'👾',
        type:'奇策型',
        stats:'HP 70<br>SPIN 100<br>SPEED 16<br>MASS 0.9',
        skill:'👾 ファントム · 加速しながら圧をかけ続ける。',
        pitch:'角度とドリフトラインを頼りに生きる、外周圧が鋭いハンター型。',
        traits:['外周からの立て直しが速い','バースト展開が鋭い','ミス許容が低い']
      },
      {
        icon:'✦',
        type:'破陣型',
        stats:'HP 78<br>SPIN 98<br>SPEED 15<br>MASS 1.1',
        skill:'✦ フライチャージ · 破線速度は高いが安定性は低い。',
        pitch:'正面の発射線を掴んだ瞬間に成果へ変える、さらに攻撃的な派生型。',
        traits:['開幕が爆発的','追撃速度が高い','止められると失速しやすい']
      },
      {
        icon:'☄',
        type:'襲撃型',
        stats:'HP 66<br>SPIN 104<br>SPEED 17<br>MASS 0.8',
        skill:'☄ ファントム · さらに鋭い外周狩りとバースト展開。',
        pitch:'危険な壁際を獲物に変える、終盤の切り返しが凶悪なドリフト捕食者。',
        traits:['危険な壁面で最強','逆転圧が非常に高い','耐久は最も低い']
      }
    ]
  };

  root.config.textLocales = {
    en:textEn,
    zh:textZh,
    ja:textJa
  };

  root.config.text = cloneLocale(textEn);

  root.config.contentLocales = {
    zh:{
      arenas:{
        circle_bowl:{ label:'圆形碗场' },
        heart_bowl:{ label:'心形碗场' },
        hex_bowl:{ label:'六角碗场' }
      },
      tops:{
        impact:{ name:'冲击' },
        armor:{ name:'装甲' },
        trick:{ name:'诡步' },
        impact_breaker:{ name:'破阵' },
        trick_raider:{ name:'掠袭' }
      },
      research:{
        spin_core:{
          label:'旋转核心',
          description:'提高所有陀螺的最大转力储备。',
          statLabel:'最大 SPIN',
          levels:[
            { preview:'最大 SPIN +4%' },
            { preview:'最大 SPIN +8%' },
            { preview:'最大 SPIN +12%' },
            { preview:'最大 SPIN +16%' }
          ]
        },
        guard_frame:{
          label:'护框结构',
          description:'强化外环结构，让你更稳地扛住碰撞。',
          statLabel:'最大 HP',
          levels:[
            { preview:'最大 HP +3%' },
            { preview:'最大 HP +6%' },
            { preview:'最大 HP +9%' },
            { preview:'最大 HP +12%' }
          ]
        },
        burst_relay:{
          label:'爆发中继',
          description:'提高爆发积累速度，让技能更早上线。',
          statLabel:'爆发积累',
          levels:[
            { preview:'爆发积累 +5%' },
            { preview:'爆发积累 +10%' },
            { preview:'爆发积累 +15%' },
            { preview:'爆发积累 +20%' }
          ]
        }
      },
      roadRanks:{
        rank_i:{ label:'RANK I', description:'基础赛事调校与标准奖励。' },
        rank_ii:{ label:'RANK II', description:'敌方续航更强，SCRAP 奖励更高。' },
        rank_iii:{ label:'RANK III', description:'最高压力的征途段位，同时拥有最高奖励倍率。' }
      },
      enemyPresets:{
        armor_standard:{ label:'装甲锚点' },
        trick_standard:{ label:'诡步猎手' },
        impact_standard:{ label:'冲击重拳' },
        armor_ram:{ label:'装甲冲槌' },
        trick_drifter:{ label:'诡步漂移' },
        impact_blitz:{ label:'冲击闪击' }
      },
      modifiers:{
        standard:{ label:'标准', description:'没有额外规则。' },
        overclock:{ label:'超频', description:'双方都以更高的爆发积累开局。' },
        ironwall:{ label:'铁壁', description:'敌方耐久获得强化。' },
        sudden_death:{ label:'骤死', description:'耐久更低，回合更快。' },
        burst_rush:{ label:'爆发猛冲', description:'玩家以更接近爆发技能的状态起手。' },
        heavy_floor:{ label:'重压地板', description:'更重的地面阻力会奖励控场。' },
        launch_surge:{ label:'起步过载', description:'双方一开局就拥有更快的爆发压力。' },
        grind_core:{ label:'碾压核心', description:'更重的脚感让对局变成控场拉锯。' },
        low_spin:{ label:'低转储备', description:'更低的转力储备会放大每一次失误。' }
      },
      challengeRoad:{
        'node-1':{ name:'开场定序', chapterLabel:'预选阶段', previewLabel:'开场定序', previewDesc:'一场基准对决，先让玩家重新找回稳控中圈的感觉。' },
        'node-2':{ name:'心形切入', chapterLabel:'预选阶段', previewLabel:'心形切入', previewDesc:'心形碗场里的角度压迫，会惩罚每一次草率发射。' },
        'node-3':{ name:'红线关口', chapterLabel:'预选阶段', previewLabel:'章节首领', previewDesc:'第一场检查点对决。爆发节奏更快，正面碰撞压力更强。' },
        'node-4':{ name:'破甲试炼', chapterLabel:'场地巡回', previewLabel:'解锁战', previewDesc:'更硬的装甲变体会借心形碗场逼你做出更重的走线承诺。' },
        'node-5':{ name:'紧迫时限', chapterLabel:'场地巡回', previewLabel:'六角漂移', previewDesc:'漂移型诡步预设加上更低转储备，会严惩凌乱的贴墙脱出。' },
        'node-6':{ name:'压地强攻', chapterLabel:'场地巡回', previewLabel:'检查点首领', previewDesc:'第二场检查点对决。更快的爆发压力，会把六角碗场变成一场短跑战。' },
        'node-7':{ name:'争夺中圈', chapterLabel:'宿敌连战', previewLabel:'宿敌压迫', previewDesc:'回到圆形碗场后，漂移空间更少，你必须更稳地咬住中心。' },
        'node-8':{ name:'破线复仇', chapterLabel:'宿敌连战', previewLabel:'复仇战', previewDesc:'一场更干净的再战，用来检验你是否真的读懂了诡步对局。' },
        'node-9':{ name:'半决强碰', chapterLabel:'冠军决赛', previewLabel:'半决赛', previewDesc:'先经受一场偏控场的半决赛，再迎来最终的撞击冲刺。' },
        'node-10':{ name:'王冠决战', chapterLabel:'冠军决赛', previewLabel:'决赛', previewDesc:'最终冠军战。节奏更快、路线更险，没有任何安全余量。' }
      }
    },
    ja:{
      arenas:{
        circle_bowl:{ label:'サークルボウル' },
        heart_bowl:{ label:'ハートボウル' },
        hex_bowl:{ label:'ヘックスボウル' }
      },
      tops:{
        impact:{ name:'インパクト' },
        armor:{ name:'アーマー' },
        trick:{ name:'トリック' },
        impact_breaker:{ name:'ブレイカー' },
        trick_raider:{ name:'レイダー' }
      },
      research:{
        spin_core:{
          label:'スピンコア',
          description:'すべてのトップの最大スピン備蓄を引き上げる。',
          statLabel:'最大 SPIN',
          levels:[
            { preview:'最大 SPIN +4%' },
            { preview:'最大 SPIN +8%' },
            { preview:'最大 SPIN +12%' },
            { preview:'最大 SPIN +16%' }
          ]
        },
        guard_frame:{
          label:'ガードフレーム',
          description:'外周フレームを補強し、被弾後の踏ん張りを安定させる。',
          statLabel:'最大 HP',
          levels:[
            { preview:'最大 HP +3%' },
            { preview:'最大 HP +6%' },
            { preview:'最大 HP +9%' },
            { preview:'最大 HP +12%' }
          ]
        },
        burst_relay:{
          label:'バーストリレー',
          description:'バースト蓄積を速め、スキルの立ち上がりを早める。',
          statLabel:'BURST 蓄積',
          levels:[
            { preview:'BURST 蓄積 +5%' },
            { preview:'BURST 蓄積 +10%' },
            { preview:'BURST 蓄積 +15%' },
            { preview:'BURST 蓄積 +20%' }
          ]
        }
      },
      roadRanks:{
        rank_i:{ label:'RANK I', description:'基本の大会調整と標準報酬。' },
        rank_ii:{ label:'RANK II', description:'敵の持久力が増し、SCRAP の配当も重くなる。' },
        rank_iii:{ label:'RANK III', description:'最大報酬倍率と引き換えに、終盤級の圧力が常にかかる。' }
      },
      enemyPresets:{
        armor_standard:{ label:'アーマーアンカー' },
        trick_standard:{ label:'トリックハンター' },
        impact_standard:{ label:'インパクトブルーザー' },
        armor_ram:{ label:'アーマーラム' },
        trick_drifter:{ label:'トリックドリフター' },
        impact_blitz:{ label:'インパクトブリッツ' }
      },
      modifiers:{
        standard:{ label:'スタンダード', description:'特別なルールなし。' },
        overclock:{ label:'オーバークロック', description:'両者とも高いバースト蓄積で開始する。' },
        ironwall:{ label:'アイアンウォール', description:'敵の耐久が強化される。' },
        sudden_death:{ label:'サドンデス', description:'HP が低く、ラウンド進行が速い。' },
        burst_rush:{ label:'バーストラッシュ', description:'プレイヤーはバーストスキルに近い状態で開幕する。' },
        heavy_floor:{ label:'ヘビーフロア', description:'重い床摩擦がコントロールを報いる。' },
        launch_surge:{ label:'ローンチサージ', description:'両者とも序盤から高いバースト圧を持つ。' },
        grind_core:{ label:'グラインドコア', description:'重い足回りが試合をコントロールの削り合いに変える。' },
        low_spin:{ label:'ロースピン', description:'少ないスピン備蓄が一つひとつのミスを重くする。' }
      },
      challengeRoad:{
        'node-1':{ name:'開幕シード', chapterLabel:'予選', previewLabel:'開幕シード', previewDesc:'まずは基準戦。安定して中央を取る感覚を取り戻す。' },
        'node-2':{ name:'ハートカット', chapterLabel:'予選', previewLabel:'ハートカット', previewDesc:'ハートボウルでの角度圧が、雑な発射を容赦なく咎める。' },
        'node-3':{ name:'レッドラインゲート', chapterLabel:'予選', previewLabel:'チャプターボス', previewDesc:'最初のチェックポイント戦。高いバースト速度と正面衝突が主役。' },
        'node-4':{ name:'ガードブレイク', chapterLabel:'アリーナサーキット', previewLabel:'アンロック戦', previewDesc:'さらに硬いアーマー派生が、ハートボウルで重いライン選択を迫る。' },
        'node-5':{ name:'タイトクロック', chapterLabel:'アリーナサーキット', previewLabel:'ヘックスドリフト', previewDesc:'ドリフト型トリックと低スピン備蓄が、壁際の雑な離脱を罰する。' },
        'node-6':{ name:'フロアプレス', chapterLabel:'アリーナサーキット', previewLabel:'チェックポイントボス', previewDesc:'二つ目のチェックポイント戦。速いバースト圧がヘックスボウルを短距離戦に変える。' },
        'node-7':{ name:'センタークレーム', chapterLabel:'ライバルシリーズ', previewLabel:'ライバル圧力', previewDesc:'サークルボウルへ戻ると、漂う余地は少なく、中央維持の精度が問われる。' },
        'node-8':{ name:'ブレイクライン', chapterLabel:'ライバルシリーズ', previewLabel:'リベンジデュエル', previewDesc:'より純度の高い再戦。トリック対面を本当に理解したかが試される。' },
        'node-9':{ name:'セミクラッシュ', chapterLabel:'チャンピオンシップ', previewLabel:'準決勝', previewDesc:'最終衝突スプリントの前に、リング支配を問う準決勝が待つ。' },
        'node-10':{ name:'クラウンクラッシュ', chapterLabel:'チャンピオンシップ', previewLabel:'ファイナル', previewDesc:'最終決戦。テンポは速く、ルートは不安定で、逃げ場はない。' }
      }
    }
  };
})();
