(function(){
  const root = window.SpinClash;
  root.config.text = {
    titleMain:'SPIN CLASH',
    titleSub:'ARENA DUEL',
    titleTagline:'Master short, explosive top battles in a static web arena.',
    enterBattle:'ENTER BATTLE',
    loadoutTitle:'SELECT YOUR TOP',
    quickBattleSubtitle:'QUICK BATTLE',
    challengeSubtitle:'CHALLENGE ROAD',
    arenaOptions:['CIRCLE BOWL','HEART BOWL','HEX BOWL'],
    fightButton:'START MATCH',
    challengeButton:'ENTER ROAD',
    roundNext:'Next round starts shortly',
    replay:'PLAY AGAIN',
    nextNode:'NEXT NODE',
    retryNode:'RETRY NODE',
    roadClear:'ROAD CLEAR',
    rematch:'CHANGE TOP',
    rewardDouble:'DOUBLE REWARD',
    rewardClaimed:'DOUBLE CLAIMED',
    rewardContinue:'CONTINUE +AD',
    shareResult:'SHARE RESULT',
    quickMode:'QUICK BATTLE',
    challengeMode:'CHALLENGE ROAD',
    challengeLocked:'Clear the current node to unlock the next duel.',
    challengeComplete:'Road clear complete. Replay for better rewards.',
    challengeFail:'Challenge failed. Use one continue or retry the node.',
    challengeContinueUsed:'Continue used for this node.',
    unlockArena:'UNLOCKED',
    unlockTop:'TOP UNLOCKED',
    unlockTopReward:'ROAD REWARD UNLOCKED',
    trialArena:'TRIAL ACTIVE',
    lockedArena:'LOCKED',
    lockedTop:'LOCKED',
    playerRole:'YOU',
    enemyRole:'CPU',
    hp:'HP',
    spin:'SPIN',
    burst:'BURST',
    dashName:'DASH',
    dashIcon:'⚡',
    swapIcon:'⇄',
    swapLabel:'SWAP',
    loadoutHintQuick:'Choose any arena and top for a one-off duel.',
    loadoutHintChallenge:'Battle through fixed nodes with modifiers and persistent rewards.',
    storageNoticeSession:'SAVE MODE: SESSION ONLY. PROGRESS MAY NOT SURVIVE A NEW TAB.',
    storageNoticeWindowName:'SAVE MODE: THIS TAB ONLY. PROGRESS MAY NOT SURVIVE A NEW WINDOW.',
    storageNoticeMemory:'SAVE MODE: TEMPORARY ONLY. PROGRESS WILL BE LOST ON RELOAD.',
    sharePrefix:'Spin Clash result',
    currencyLabel:'SCRAP',
    cards:[
      {icon:'⚔',type:'IMPACT',stats:'HP 85<br>Spin 95<br>Speed 14<br>Mass 1.2',skill:'⚔ Fly Charge · Surge straight at the target.'},
      {icon:'🛡',type:'ARMOR',stats:'HP 120<br>Spin 75<br>Speed 10<br>Mass 1.5',skill:'🛡 Shield · Brief defensive barrier.'},
      {icon:'👾',type:'TRICK',stats:'HP 70<br>Spin 100<br>Speed 16<br>Mass 0.9',skill:'👾 Phantom · Speed burst and pressure.'}
    ]
  };
})();
