(function(){
  const root = window.SpinClash;

  function cloneLocale(value){
    if(Array.isArray(value)) return value.map(cloneLocale);
    if(value && typeof value === 'object'){
      const result = {};
      Object.keys(value).forEach(function(key){
        result[key] = cloneLocale(value[key]);
      });
      return result;
    }
    return value;
  }

  const textEn = {
    titleMain:'SPIN CLASH',
    titleSub:'ARENA DUEL',
    titleTagline:'Short, violent spin duels with no dead time and no backend baggage.',
    titleProgressLabel:'PATH STATUS',
    titleGoalLabel:'NEXT TARGET',
    titleQuickBattle:'QUICK BATTLE',
    titleWorkshop:'WORKSHOP',
    settingsTitle:'SETTINGS',
    backButton:'BACK',
    routeFromLabel:'FROM',
    homeRoute:'HOME',
    continuePath:'CONTINUE PATH',
    enterBattle:'CONTINUE PATH',
    loadoutTitle:'SELECT YOUR TOP',
    featuredTopTitle:'SELECTED TOP',
    featuredTraitsTitle:'TRACK TRAITS',
    homeTopTitle:'CURRENT TOP',
    homeTopCountLabel:'UNLOCKED',
    homeTopUnlocked:'UNLOCKED',
    homeTopLocked:'LOCKED',
    topSourceStarter:'STARTER',
    topSourceRoadReward:'ROAD REWARD',
    topSourceWorkshop:'SCRAP UNLOCK',
    topSourceRoadShop:'ROAD REWARD / SCRAP UNLOCK',
    topUnlockRoadRank:'Clear {rank} to unlock',
    topUnlockShopCost:'Tap here to buy for {cost} {currency}',
    homeTopLockedSkill:'Silhouette only. Full ability data unlocks later.',
    homeTopLockedHint:'Unlock this top to reveal its full shape and material finish.',
    homeTopLockedHintRoad:'Clear deeper Championship Path nodes to reveal this top.',
    homeTopLockedHintShop:'Open Loadout and tap this top card when you have enough SCRAP.',
    homeTopLockedHintRoadShop:'Unlock this top on the Path or tap its Loadout card to buy it with SCRAP.',
    topPurchaseConfirmKicker:'UNLOCK TOP',
    topPurchaseNeedMoreKicker:'SCRAP SHORT',
    topPurchaseConfirmCopy:'Spend {cost} {currency} now to unlock {top}. This unlock is permanent in your local save.',
    topPurchaseEarnCopy:'Need more {currency}. Push Championship Path nodes, claim match rewards, and grab first-clear bonuses to build your balance.',
    topPurchaseCostLine:'PRICE {cost} {currency} - BALANCE {balance} {currency}',
    topPurchaseShortfallLine:'PRICE {cost} {currency} - SHORT {shortfall} {currency}',
    topPurchaseConfirmButton:'BUY NOW',
    topPurchaseCancelButton:'NOT YET',
    topPurchaseCloseButton:'GOT IT',
    titleBuildVersion:'Version 1.1.0',
    titleCopyright:'© 2026 Hakuro Kudo / Lumos',
    homeTopPrev:'<',
    homeTopNext:'>',
    homeTopEmpty:'Choose an unlocked top to preview its strengths.',
    quickBattleSubtitle:'QUICK BATTLE',
    quickArenaTitle:'SELECTED ARENA',
    quickArenaUnlocked:'UNLOCKED',
    quickArenaLocked:'LOCKED',
    quickArenaDescriptions:{
      circle_bowl:'Balanced circular bowl with the cleanest center-control reads.',
      heart_bowl:'Heart bowl that exaggerates angle pressure and edge decisions.',
      hex_bowl:'Hex bowl with harsher rebounds and tighter escape lanes.',
      cyclone_bowl:'Steeper circle bowl with an earlier hot rim and faster center collapse.',
      rose_bowl:'Pinched heart bowl that rewards angled launches and punishes loose recoveries.',
      octa_bowl:'Eight-wall bowl with chained redirects and shorter hazard-safe lanes.'
    },
    quickTopTitle:'DEPLOYED TOP',
    quickTopLocked:'LOCKED',
    quickTopReady:'READY',
    quickTopOwnedStarterHint:'Ready from start',
    quickTopOwnedRoadHint:'Road reward secured',
    quickTopOwnedShopHint:'SCRAP unlock secured',
    quickTopOwnedReadyHint:'Ready for quick battle',
    quickTopPathAction:'GO TO PATH',
    quickTopEarnAction:'EARN SCRAP',
    quickTopWalletNeedLine:'Balance {balance} {currency} · Price {cost} {currency}',
    quickTopWalletOwnedLine:'Balance {balance} {currency}',
    quickTopLockedHint:'Locked tops cannot enter quick battle.',
    homeRouteLockedHint:'The previewed top is locked. Switch back to an unlocked top before entering battle routes.',
    quickStartBlockedHint:'You cannot enter battle with a locked top. Return Home and switch to an unlocked top.',
    quickStartBlockedButton:'TOP LOCKED',
    quickStartReadyHint:'Arena ready. Launch when ready.',
    quickStartArenaLockedHint:'This arena is locked. Start to unlock it or activate a trial.',
    quickStartArenaUnlockButton:'UNLOCK + START',
    quickStartArenaUnlockHint:'Spend {cost} SCRAP to unlock this arena, then begin immediately.',
    quickStartArenaTrialButton:'WATCH AD TRIAL',
    quickStartArenaTrialHint:'SCRAP is short. Watch an ad to activate a session trial for this arena.',
    challengeSubtitle:'CHAMPIONSHIP PATH',
    arenaOptions:['Azure Ring Court','Scarlet Heart Verge','Shard Hex Array','Tempest Maw Depth','Thornbloom Snare','Prism Arcade'],
    fightButton:'START MATCH',
    challengeButton:'ENTER PATH',
    roundNext:'Next round starts shortly',
    replay:'PLAY AGAIN',
    nextNode:'NEXT NODE',
    retryNode:'RETRY NODE',
    roadClear:'ROAD CLEAR',
    rematch:'CHANGE TOP',
    rewardDouble:'DOUBLE REWARD',
    rewardClaimed:'DOUBLE CLAIMED',
    rewardContinue:'CONTINUE +AD',
    rewardBusy:'REWARD REQUEST SENT. PLEASE WAIT A MOMENT.',
    rewardLoading:'REWARD IS STILL LOADING. TRY AGAIN IN A SECOND.',
    rewardUnavailable:'REWARD NOT AVAILABLE RIGHT NOW.',
    rewardDeclined:'NO REWARD WAS GRANTED.',
    rewardError:'REWARD FLOW FAILED.',
    rewardDoubleBusy:'DOUBLE REWARD REQUEST SENT. PLEASE WAIT A MOMENT.',
    rewardDoubleLoading:'DOUBLE REWARD IS STILL LOADING. TRY AGAIN IN A SECOND.',
    rewardDoubleUnavailable:'DOUBLE REWARD DID NOT COME THROUGH. YOU STILL KEEP THE BASE PAYOUT AND CAN TRY AGAIN NEXT MATCH.',
    rewardDoubleDeclined:'DOUBLE REWARD DID NOT ACTIVATE. TAP AGAIN IF YOU WANT TO TRY ONCE MORE.',
    rewardDoubleError:'DOUBLE REWARD DID NOT COME THROUGH. YOU STILL KEEP THE BASE PAYOUT AND CAN TRY AGAIN NEXT MATCH.',
    rewardContinueBusy:'THE REQUEST TO CONTINUE THIS CHALLENGE IS ALREADY IN PROGRESS. PLEASE WAIT A MOMENT.',
    rewardContinueLoading:'THE OPTION TO CONTINUE THIS CHALLENGE IS STILL LOADING. TRY AGAIN IN A SECOND.',
    rewardContinueUnavailable:'YOU COULD NOT CONTINUE THIS CHALLENGE THIS TIME. THIS RUN ENDS HERE, YOUR PAYOUT STILL COUNTS, AND YOU CAN TRY AGAIN ON YOUR NEXT CHALLENGE.',
    rewardContinueDeclined:'THIS CHALLENGE WAS NOT RESUMED. TAP AGAIN IF YOU WANT TO TRY ONCE MORE.',
    rewardContinueError:'YOU COULD NOT CONTINUE THIS CHALLENGE THIS TIME. THIS RUN ENDS HERE, YOUR PAYOUT STILL COUNTS, AND YOU CAN TRY AGAIN ON YOUR NEXT CHALLENGE.',
    rewardTrialBusy:'ARENA TRIAL REQUEST SENT. PLEASE WAIT A MOMENT.',
    rewardTrialLoading:'ARENA TRIAL IS STILL LOADING. TRY AGAIN IN A SECOND.',
    rewardTrialUnavailable:'ARENA TRIAL COULD NOT START THIS TIME. TRY AGAIN LATER, OR PICK A DIFFERENT ARENA FOR NOW.',
    rewardTrialDeclined:'ARENA TRIAL DID NOT START. TAP AGAIN IF YOU WANT TO TRY THIS ARENA ONCE MORE.',
    rewardTrialError:'ARENA TRIAL COULD NOT START THIS TIME. TRY AGAIN LATER, OR PICK A DIFFERENT ARENA FOR NOW.',
    shareResult:'SHARE RESULT',
    resultBreakdownBase:'BASE',
    resultBreakdownNode:'NODE',
    resultBreakdownFirstClear:'FIRST CLEAR',
    resultBreakdownRank:'RANK BONUS',
    resultNextNodeLabel:'Next',
    resultRetryLabel:'Retry',
    resultRoadLabel:'Road',
    resultArenaLabel:'Arena',
    resultNodeLabel:'Node',
    resultReasonLabel:'Finish',
    resultShareLabel:'Share moment',
    resultRewardLabel:'Reward',
    resultReturnToPath:'RETURN TO PATH',
    resultReturnToQuick:'RETURN TO QUICK',
    resultReturnToHome:'RETURN HOME',
    resultAdjustPath:'ADJUST PATH LOADOUT',
    resultAdjustQuick:'ADJUST QUICK LOADOUT',
    resultAdjustHome:'CHANGE TOP',
    quickMode:'QUICK BATTLE',
    challengeMode:'CHAMPIONSHIP PATH',
    workshopToggle:'OPEN WORKSHOP',
    workshopClose:'CLOSE WORKSHOP',
    workshopTitle:'WORKSHOP RESEARCH',
    workshopHint:'Permanent SCRAP upgrades for your roster.',
    workshopBuy:'UPGRADE',
    workshopMaxed:'MAXED',
    workshopLocked:'MORE SCRAP NEEDED',
    workshopUnlocked:'RESEARCH UPGRADED',
    workshopLevel:'LV',
    workshopCurrent:'ACTIVE',
    workshopNext:'NEXT',
    settingsHint:'Language and audio preferences.',
    settingsLanguageLabel:'LANGUAGE',
    settingsMusicLabel:'MUSIC',
    settingsSfxLabel:'SFX',
    settingsToggleOn:'ON',
    settingsToggleOff:'OFF',
    settingsMusicOn:'MUSIC: ON',
    settingsMusicOff:'MUSIC: OFF',
    settingsSfxOn:'SFX: ON',
    settingsSfxOff:'SFX: OFF',
    roadRankTitle:'ROAD RANK',
    roadRankLocked:'LOCKED',
    roadRankUnlocked:'UNLOCKED',
    roadRankHint:'Championship tuning and reward band.',
    roadRankRewardLabel:'Reward',
    roadRankRewardTopLabel:'Top',
    challengeCurrentTopTitle:'CURRENT LOADOUT',
    challengeArenaInfo:'Arena {value}',
    challengeEnemyInfo:'Enemy {value}',
    challengeRuleInfo:'Rule {value}',
    challengeRewardInfo:'Reward {value}',
    challengeFirstClearInfo:'First Clear +{value}',
    challengeRankInfo:'{rank} x{multiplier}',
    challengeCheckpointInfo:'Checkpoint on clear',
    challengeLocked:'Clear the current node to unlock the next duel.',
    challengeComplete:'Road clear complete. Replay for better rewards.',
    challengeFail:'Challenge failed. Use one continue or retry the node.',
    challengeContinueUsed:'Continue used for this node.',
    unlockArena:'UNLOCKED',
    unlockTop:'TOP UNLOCKED',
    unlockTopReward:'ROAD REWARD UNLOCKED',
    trialArena:'TRIAL ACTIVE',
    lockedArena:'LOCKED',
    lockedTop:'LOCKED',
    playerRole:'YOU',
    enemyRole:'CPU',
    statusReady:'READY',
    statusGuarding:'GUARD',
    statusIntentSkill:'SKILL',
    statusIntentDash:'DASH',
    statusIntentGuard:'GUARD',
    hp:'HP',
    spin:'SPIN',
    burst:'BURST',
    dashName:'DASH',
    dashIcon:'⚡',
    guardName:'GUARD',
    guardIcon:'🛡',
    swapIcon:'⇄',
    swapLabel:'SWAP',
    loadoutHintQuick:'Choose an arena for a one-off duel. Your current top is confirmed from Home.',
    loadoutHintChallenge:'Battle through fixed nodes with modifiers and persistent rewards.',
    storageNoticeSession:'SAVE MODE: SESSION ONLY. PROGRESS MAY NOT SURVIVE A NEW TAB.',
    storageNoticeWindowName:'SAVE MODE: THIS TAB ONLY. PROGRESS MAY NOT SURVIVE A NEW WINDOW.',
    storageNoticeMemory:'SAVE MODE: TEMPORARY ONLY. PROGRESS WILL BE LOST ON RELOAD.',
    shareTitle:'Spin Clash',
    sharePrefix:'Spin Clash result',
    shareMoments:{
      road_clear:'ROAD CLEAR',
      challenge_clear:'CHALLENGE CLEAR',
      ring_out:'RING OUT',
      perfect_win:'PERFECT WIN',
      close_loss:'CLOSE LOSS',
      victory:'VICTORY',
      defeat:'DEFEAT'
    },
    shareTemplates:{
      road_clear:'{title}: cleared the full Challenge Road in {arena} with {top}.',
      challenge_clear:'{title}: cleared Node {node} in {arena} with {top}.',
      ring_out:'{title}: landed a ring-out finish in {arena} with {top}.',
      perfect_win:'{title}: won {scorePlayer}-{scoreEnemy} in {arena} with {top}.',
      close_loss:'{title}: lost {scorePlayer}-{scoreEnemy} in {arena}. Rematch time.',
      victory:'{title}: won in {arena} with {top}.',
      defeat:'{title}: battled in {arena} with {top}.'
    },
    currencyLabel:'SCRAP',
    walletLabel:'BALANCE',
    localeButtons:{
      en:'EN',
      zh:'中文',
      ja:'日本語'
    },
    hintAim:'Drag to aim, then release to launch.',
    hintActive:'SPACE to dash | E to guard | Q to use your burst skill.',
    hintSkillReady:'Q READY',
    roundLabel:'ROUND',
    roundWinPlayer:'YOU WIN!',
    roundWinEnemy:'ENEMY WINS',
    roundWinDraw:'DRAW',
    roundReasonRingOut:'Ring Out',
    roundReasonSpinOut:'Spin Out',
    roundReasonHpBreak:'HP Break',
    roundReasonTimeUp:'Time Up - HP Check',
    fightCallout:'FIGHT!',
    nodeLocked:'Node locked.',
    checkpointLabel:'CHECKPOINT',
    tierBoss:'BOSS',
    tierFinal:'FINAL',
    resumeLabel:'Resume',
    noBonus:'NO BONUS',
    battleIntroQuickStage:'QUICK BATTLE',
    battleIntroNodeLabel:'NODE',
    battleIntroVersus:' VS ',
    skillLabels:{
      'Fly Charge':'Fly Charge',
      'Fortress Pulse':'Fortress Pulse',
      'Phantom':'Phantom'
    },
    skillMessages:{
      player:{
        'Fly Charge':'Fly Charge!',
        'Fortress Pulse':'Fortress Pulse!',
        'Phantom':'Phantom!'
      },
      enemy:{
        'Fly Charge':'Enemy used Fly Charge!',
        'Fortress Pulse':'Enemy used Fortress Pulse!',
        'Phantom':'Enemy used Phantom!'
      }
    },
    messageDash:'DASH!',
    messageGuard:'GUARD!',
    messageBurstOrb:'+55 BURST',
    messageHeavyCollision:'Heavy Collision!',
    messageSuperImpact:'Super Impact!!',
    messagePlayerRingOut:'You were knocked out of the arena!',
    messageEnemyRingOut:'The opponent flew out of the arena!',
    copyShareText:'Copy share text',
    shareCardPlayerTop:'PLAYER TOP',
    shareCardEnemyTop:'ENEMY TOP',
    shareCardChallengeRoad:'CHALLENGE ROAD',
    shareCardNode:'NODE',
    shareCardOpenMatch:'OPEN MATCH',
    shareCardQuickBattle:'QUICK BATTLE',
    shareCardVictory:'VICTORY',
    shareCardDefeat:'DEFEAT',
    cards:[
      {
        icon:'⚔',
        type:'ASSAULT',
        stats:'HP 85<br>SPIN 95<br>SPEED 14<br>MASS 1.2',
        skill:'⚔ Fly Charge · Surge straight at the target.',
        pitch:'Hard entry top that turns the first clean angle into momentum.',
        traits:['Front-load damage','Punishes loose launches','Best when you force center contact']
      },
      {
        icon:'🛡',
        type:'BULWARK',
        stats:'HP 120<br>SPIN 75<br>SPEED 10<br>MASS 1.5',
        skill:'🛡 Fortress Pulse · Anchor the lane and blast the rival outward.',
        pitch:'Heavy control pick that stabilizes itself and wins space with a shock pulse.',
        traits:['Strong anti-rush pulse','Best at reclaiming center','Slow to reposition']
      },
      {
        icon:'👾',
        type:'SKIRMISH',
        stats:'HP 70<br>SPIN 100<br>SPEED 16<br>MASS 0.9',
        skill:'👾 Phantom · Speed burst and pressure.',
        pitch:'Angle-hunting top that lives off drift lines and edge pressure.',
        traits:['Fast edge recovery','Sharp burst tempo','Low mistake tolerance']
      },
      {
        icon:'✦',
        type:'ASSAULT',
        stats:'HP 78<br>SPIN 98<br>SPEED 15<br>MASS 1.1',
        skill:'✦ Fly Charge · Faster line break with lower stability.',
        pitch:'Aggressive variant that cashes in on direct launch lines immediately.',
        traits:['Explosive opener','Higher chase speed','Falls off if stalled']
      },
      {
        icon:'☄',
        type:'SKIRMISH',
        stats:'HP 66<br>SPIN 104<br>SPEED 17<br>MASS 0.8',
        skill:'☄ Phantom · Sharper edge hunting and burst tempo.',
        pitch:'Predatory drift variant built for arena abuse and clutch scrambles.',
        traits:['Best on risky walls','Excellent comeback pressure','Lowest durability']
      },
      {
        icon:'🜂',
        type:'ASSAULT',
        stats:'HP 92<br>SPIN 88<br>SPEED 13<br>MASS 1.3',
        skill:'🜂 Fly Charge · Lower angle speed, stronger lane hold.',
        pitch:'Stable impact frame that keeps its nose buried in center contact.',
        traits:['Wider launch window','Keeps contact longer','Lower burst pace']
      },
      {
        icon:'✺',
        type:'ASSAULT',
        stats:'HP 74<br>SPIN 102<br>SPEED 17<br>MASS 0.9',
        skill:'✺ Fly Charge · Hyper-fast strike with a short burnout window.',
        pitch:'Glass-cannon charger that explodes through one clean line and fades if stalled.',
        traits:['Fastest impact entry','Short dash window','Needs decisive angles']
      },
      {
        icon:'⛏',
        type:'ASSAULT',
        stats:'HP 98<br>SPIN 84<br>SPEED 12<br>MASS 1.4',
        skill:'⛏ Fly Charge · Heavy slam that keeps collision pressure active longer.',
        pitch:'Dense impact shell that trades some tempo for brutal sustained contact.',
        traits:['Heavy collision grip','Great versus guards','Slowest impact recovery']
      },
      {
        icon:'⛨',
        type:'BULWARK',
        stats:'HP 128<br>SPIN 72<br>SPEED 9<br>MASS 1.6',
        skill:'⛨ Fortress Pulse · Deep anchor pulse with extra outward force.',
        pitch:'Full-wall defender built to survive rushes and reset the center every time.',
        traits:['Most stable pulse','Huge anti-rush window','Very low chase speed']
      },
      {
        icon:'⬡',
        type:'BULWARK',
        stats:'HP 104<br>SPIN 86<br>SPEED 12<br>MASS 1.2',
        skill:'⬡ Fortress Pulse · Cleaner counter-pulse with faster re-entry.',
        pitch:'Mobile armor hybrid that converts defense into an immediate retake line.',
        traits:['Balanced armor frame','Fast center retakes','Lower stall power']
      },
      {
        icon:'🗿',
        type:'BULWARK',
        stats:'HP 136<br>SPIN 70<br>SPEED 8<br>MASS 1.7',
        skill:'🗿 Fortress Pulse · Massive shock pulse with extreme self-anchor.',
        pitch:'Maximum-weight control body that dares the rival to collide first.',
        traits:['Highest raw walling','Massive knockback','Weakest pursuit']
      },
      {
        icon:'✧',
        type:'BULWARK',
        stats:'HP 98<br>SPIN 90<br>SPEED 13<br>MASS 1.1',
        skill:'✧ Fortress Pulse · Flexible pulse timing with smoother carry-through.',
        pitch:'Reflective armor shell that slides out of bad contact and answers back.',
        traits:['Best armor mobility','Safer resets','Less pure stopping power']
      },
      {
        icon:'☣',
        type:'SKIRMISH',
        stats:'HP 64<br>SPIN 106<br>SPEED 18<br>MASS 0.8',
        skill:'☣ Phantom · Toxic drift burst that keeps clipping the flank.',
        pitch:'Needle-like trick variant that wins by repeated edge bites and poison tempo.',
        traits:['Relentless flank pressure','Very fast edge loops','Punishes hesitation']
      },
      {
        icon:'◎',
        type:'SKIRMISH',
        stats:'HP 76<br>SPIN 101<br>SPEED 15<br>MASS 0.9',
        skill:'◎ Phantom · Longer orbit phase with cleaner wall resets.',
        pitch:'Control-minded trick shell that circles wider and chooses safer return lines.',
        traits:['Longest phantom uptime','Strong arena resets','Lower burst impact']
      },
      {
        icon:'⌁',
        type:'SKIRMISH',
        stats:'HP 60<br>SPIN 108<br>SPEED 19<br>MASS 0.8',
        skill:'⌁ Phantom · Chaotic side-cut with the sharpest lateral break.',
        pitch:'Unstable duel thief that wins by making its own impossible angle.',
        traits:['Wildest drift break','Hardest to read','Zero forgiveness']
      }
    ]
  };

  const textZh = {
    titleMain:'SPIN CLASH',
    titleSub:'竞技对决',
    titleTagline:'短局、高烈度的陀螺对决，没有拖沓，也没有后端负担。',
    titleProgressLabel:'路径进度',
    titleGoalLabel:'下一目标',
    titleQuickBattle:'快速对战',
    titleWorkshop:'工坊研究',
    settingsTitle:'设置',
    backButton:'返回',
    routeFromLabel:'来源',
    homeRoute:'主页',
    continuePath:'继续征途',
    enterBattle:'继续征途',
    loadoutTitle:'选择陀螺',
    featuredTopTitle:'当前陀螺',
    featuredTraitsTitle:'特性概览',
    homeTopTitle:'当前陀螺',
    homeTopCountLabel:'已解锁',
    homeTopUnlocked:'已解锁',
    homeTopLocked:'未解锁',
    topSourceStarter:'初始',
    topSourceRoadReward:'道路奖励',
    topSourceWorkshop:'SCRAP购买',
    topSourceRoadShop:'道路奖励 / SCRAP购买',
    topUnlockRoadRank:'通关 {rank} 后解锁',
    topUnlockShopCost:'点击此卡，花费 {cost} {currency} 购买',
    homeTopLockedSkill:'当前仅显示暗影预览，完整能力信息将在解锁后公开。',
    homeTopLockedHint:'解锁后可查看它的完整材质、轮廓与能力说明。',
    homeTopLockedHintRoad:'继续推进冠军之路更深节点后可解锁这只陀螺。',
    homeTopLockedHintShop:'进入选装页后，直接点击这张陀螺卡；SCRAP 足够时即可购买。',
    homeTopLockedHintRoadShop:'这只陀螺可在冠军之路奖励中获得，或在选装页直接花 SCRAP 购买。',
    topPurchaseConfirmKicker:'解锁陀螺',
    topPurchaseNeedMoreKicker:'SCRAP 不足',
    topPurchaseConfirmCopy:'现在花费 {cost} {currency} 解锁 {top}。确认后会永久写入当前本地存档。',
    topPurchaseEarnCopy:'当前 {currency} 不够。继续推进冠军之路、领取每场结算奖励，并争取首通奖励，就能更快攒够购买所需的 SCRAP。',
    topPurchaseCostLine:'价格 {cost} {currency} · 当前持有 {balance} {currency}',
    topPurchaseShortfallLine:'价格 {cost} {currency} · 还差 {shortfall} {currency}',
    topPurchaseConfirmButton:'现在就买',
    topPurchaseCancelButton:'再看看',
    topPurchaseCloseButton:'知道了',
    titleBuildVersion:'版本 1.1.0',
    titleCopyright:'© 2026 Hakuro Kudo / Lumos',
    homeTopPrev:'<',
    homeTopNext:'>',
    homeTopEmpty:'切换已解锁陀螺，查看它们的定位与优势。',
    quickBattleSubtitle:'快速对战',
    quickArenaTitle:'当前场地',
    quickArenaUnlocked:'已解锁',
    quickArenaLocked:'未解锁',
    quickArenaDescriptions:{
      circle_bowl:'标准圆形碗场，最容易看清中圈争夺。',
      heart_bowl:'心形碗场会放大角度压迫与边缘决策。',
      hex_bowl:'六角碗场反弹更硬，脱离路线更紧。',
      cyclone_bowl:'更陡的圆碗场，危险外圈更早开始，中圈塌缩更快。',
      rose_bowl:'收腰后的心形碗场更吃斜角发射，也更惩罚松散回收。',
      octa_bowl:'八边折返碗场会连续折射，安全走线更短。'
    },
    quickTopTitle:'出战陀螺',
    quickTopLocked:'未解锁',
    quickTopReady:'可出战',
    quickTopOwnedStarterHint:'开局即可使用',
    quickTopOwnedRoadHint:'已拿到道路奖励',
    quickTopOwnedShopHint:'已完成 SCRAP 解锁',
    quickTopOwnedReadyHint:'可以直接出战',
    quickTopPathAction:'前往冠军之路',
    quickTopEarnAction:'去赚 SCRAP',
    quickTopWalletNeedLine:'当前 {balance} {currency} · 价格 {cost} {currency}',
    quickTopWalletOwnedLine:'当前持有 {balance} {currency}',
    quickTopLockedHint:'未解锁的陀螺不能进入快速对战。',
    homeRouteLockedHint:'当前预览的陀螺尚未解锁，请先切回已解锁陀螺，再进入对战路线。',
    quickStartBlockedHint:'当前陀螺未解锁，不能出战。请回到主页切换已解锁陀螺。',
    quickStartBlockedButton:'无法出战',
    quickStartReadyHint:'场地已就绪，可以直接开战。',
    quickStartArenaLockedHint:'该场地尚未解锁，开始时会尝试解锁或进入试用。',
    quickStartArenaUnlockButton:'解锁并开始',
    quickStartArenaUnlockHint:'消耗 {cost} SCRAP 解锁该场地，并立即开始对战。',
    quickStartArenaTrialButton:'广告试玩',
    quickStartArenaTrialHint:'当前 SCRAP 不足，可看广告开启该场地的本次会话试用。',
    challengeSubtitle:'冠军之路',
    arenaOptions:['苍轮斗庭','绯心曲域','断棱角阵','岚涡深渊','棘华幽阱','八镜回廊'],
    fightButton:'开始对战',
    challengeButton:'进入征途',
    roundNext:'下一回合即将开始',
    replay:'再来一局',
    nextNode:'下一节点',
    retryNode:'重试节点',
    roadClear:'通关完成',
    rematch:'更换陀螺',
    rewardDouble:'双倍奖励',
    rewardClaimed:'双倍已领取',
    rewardContinue:'继续挑战 +广告',
    rewardBusy:'请求已经发出，请先等一下。',
    rewardLoading:'内容还在加载，等一秒再点。',
    rewardUnavailable:'当前暂时无法提供该内容。',
    rewardDeclined:'这次没有成功。',
    rewardError:'这次没有成功，请稍后再试。',
    rewardDoubleBusy:'双倍奖励正在请求中，请先等一下。',
    rewardDoubleLoading:'双倍奖励还在加载，等一秒再点。',
    rewardDoubleUnavailable:'这次没拿到双倍奖励，先按基础奖励结算。下一局还能再试。',
    rewardDoubleDeclined:'这次双倍奖励没生效。想拿双倍，再点一次就行。',
    rewardDoubleError:'这次没拿到双倍奖励，先按基础奖励结算。下一局还能再试。',
    rewardContinueBusy:'继续当前挑战的请求已经发出，请先等一下。',
    rewardContinueLoading:'继续当前挑战的机会还在加载，等一秒再点。',
    rewardContinueUnavailable:'这次没能继续当前挑战，这一场会在这里结束。奖励照常发放，下次挑战还能再试一次。',
    rewardContinueDeclined:'这次没能继续当前挑战。想回到这一场，再点一次就行。',
    rewardContinueError:'这次没能继续当前挑战，这一场会在这里结束。奖励照常发放，下次挑战还能再试一次。',
    rewardTrialBusy:'场地试玩请求已经发出，请先等一下。',
    rewardTrialLoading:'场地试玩还在加载，等一秒再点。',
    rewardTrialUnavailable:'这次没能开启场地试玩。稍后再试，或者先去其他场地。',
    rewardTrialDeclined:'这次没能开启场地试玩。想试玩这个场地，再点一次就行。',
    rewardTrialError:'这次没能开启场地试玩。稍后再试，或者先去其他场地。',
    shareResult:'分享战绩',
    resultBreakdownBase:'基础',
    resultBreakdownNode:'节点',
    resultBreakdownFirstClear:'首通',
    resultBreakdownRank:'段位加成',
    resultNextNodeLabel:'下一步',
    resultRetryLabel:'重试',
    resultRoadLabel:'征途',
    resultArenaLabel:'场地',
    resultNodeLabel:'节点',
    resultReasonLabel:'结束方式',
    resultShareLabel:'分享时刻',
    resultRewardLabel:'奖励',
    resultReturnToPath:'返回冠军之路',
    resultReturnToQuick:'返回快速对战',
    resultReturnToHome:'返回主页',
    resultAdjustPath:'返回冠军之路调整配置',
    resultAdjustQuick:'返回快速对战调整配置',
    resultAdjustHome:'更换陀螺',
    quickMode:'快速对战',
    challengeMode:'冠军之路',
    workshopToggle:'打开工坊',
    workshopClose:'收起工坊',
    workshopTitle:'工坊研究',
    workshopHint:'使用 SCRAP 进行永久研究强化。',
    workshopBuy:'升级',
    workshopMaxed:'已满级',
    workshopLocked:'SCRAP 不足',
    workshopUnlocked:'研究已升级',
    workshopLevel:'LV',
    workshopCurrent:'当前',
    workshopNext:'下一级',
    settingsHint:'语言和音频开关会立即生效，并保存到当前本地存档。',
    settingsLanguageLabel:'语言',
    settingsMusicLabel:'音乐',
    settingsSfxLabel:'音效',
    settingsToggleOn:'开启',
    settingsToggleOff:'关闭',
    settingsMusicOn:'音乐：开启',
    settingsMusicOff:'音乐：关闭',
    settingsSfxOn:'音效：开启',
    settingsSfxOff:'音效：关闭',
    roadRankTitle:'道路段位',
    roadRankLocked:'未解锁',
    roadRankUnlocked:'已解锁',
    roadRankHint:'当前赛事强度与奖励档位。',
    roadRankRewardLabel:'奖励',
    roadRankRewardTopLabel:'奖励陀螺',
    challengeCurrentTopTitle:'当前出战',
    challengeArenaInfo:'场地 {value}',
    challengeEnemyInfo:'对手 {value}',
    challengeRuleInfo:'规则 {value}',
    challengeRewardInfo:'奖励 {value}',
    challengeFirstClearInfo:'首通 +{value}',
    challengeRankInfo:'{rank} x{multiplier}',
    challengeCheckpointInfo:'通关后保存进度',
    challengeLocked:'先通过当前节点，才能解锁下一场对决。',
    challengeComplete:'冠军之路已通关，可重复挑战以获取更高奖励。',
    challengeFail:'挑战失败。你可以使用一次继续，或重试当前节点。',
    challengeContinueUsed:'本节点已使用继续。',
    unlockArena:'已解锁',
    unlockTop:'陀螺已解锁',
    unlockTopReward:'道路奖励已解锁',
    trialArena:'试用中',
    lockedArena:'未解锁',
    lockedTop:'未解锁',
    playerRole:'你',
    enemyRole:'电脑',
    statusReady:'已就绪',
    statusGuarding:'防御中',
    statusIntentSkill:'蓄技中',
    statusIntentDash:'突进中',
    statusIntentGuard:'起盾中',
    hp:'HP',
    spin:'SPIN',
    burst:'BURST',
    dashName:'冲刺',
    dashIcon:'⚡',
    guardName:'防御',
    guardIcon:'🛡',
    swapIcon:'⇄',
    swapLabel:'切换',
    loadoutHintQuick:'选择场地开始单局对战，当前陀螺由主页决定。',
    loadoutHintChallenge:'沿固定节点连续挑战，在修饰器和持久奖励中一路推进。',
    storageNoticeSession:'保存模式：仅当前会话。重新开标签页后，进度可能不会保留。',
    storageNoticeWindowName:'保存模式：仅当前标签页。打开新窗口后，进度可能不会保留。',
    storageNoticeMemory:'保存模式：临时内存。刷新页面后，进度会丢失。',
    shareTitle:'Spin Clash',
    sharePrefix:'Spin Clash 战绩',
    shareMoments:{
      road_clear:'征途通关',
      challenge_clear:'节点突破',
      ring_out:'击飞出场',
      perfect_win:'完胜',
      close_loss:'惜败',
      victory:'胜利',
      defeat:'落败'
    },
    shareTemplates:{
      road_clear:'{title}：我用 {top} 在 {arena} 打通了整条冠军之路。',
      challenge_clear:'{title}：我用 {top} 在 {arena} 突破了第 {node} 节点。',
      ring_out:'{title}：我用 {top} 在 {arena} 完成了击飞出场。',
      perfect_win:'{title}：我用 {top} 在 {arena} 以 {scorePlayer}-{scoreEnemy} 完胜。',
      close_loss:'{title}：我在 {arena} 以 {scorePlayer}-{scoreEnemy} 惜败，准备复仇。',
      victory:'{title}：我用 {top} 在 {arena} 赢下了对战。',
      defeat:'{title}：我在 {arena} 驾驭 {top} 打完了一场硬仗。'
    },
    currencyLabel:'SCRAP',
    walletLabel:'余额',
    localeButtons:{
      en:'EN',
      zh:'中文',
      ja:'日本語'
    },
    hintAim:'拖拽瞄准，松手发射。',
    hintActive:'按 SPACE 冲刺 | 按 E 防御 | 按 Q 释放爆发技能。',
    hintSkillReady:'Q 已就绪',
    roundLabel:'回合',
    roundWinPlayer:'你获胜！',
    roundWinEnemy:'对手获胜',
    roundWinDraw:'平局',
    roundReasonRingOut:'击飞出场',
    roundReasonSpinOut:'转力耗尽',
    roundReasonHpBreak:'耐久崩解',
    roundReasonTimeUp:'时间到 - 按耐久判定',
    fightCallout:'开战！',
    nodeLocked:'节点尚未解锁。',
    checkpointLabel:'检查点',
    tierBoss:'首领',
    tierFinal:'决赛',
    resumeLabel:'续接自',
    noBonus:'暂无加成',
    battleIntroQuickStage:'快速对战',
    battleIntroNodeLabel:'节点',
    battleIntroVersus:' VS ',
    skillLabels:{
      'Fly Charge':'飞冲',
      'Fortress Pulse':'堡垒脉冲',
      'Phantom':'幻袭'
    },
    skillMessages:{
      player:{
        'Fly Charge':'飞冲！',
        'Fortress Pulse':'堡垒脉冲！',
        'Phantom':'幻袭！'
      },
      enemy:{
        'Fly Charge':'敌方使出了飞冲！',
        'Fortress Pulse':'敌方使出了堡垒脉冲！',
        'Phantom':'敌方使出了幻袭！'
      }
    },
    messageDash:'冲刺！',
    messageGuard:'防御！',
    messageBurstOrb:'+55 BURST',
    messageHeavyCollision:'重击碰撞！',
    messageSuperImpact:'超强冲击！',
    messagePlayerRingOut:'你被撞出了场地！',
    messageEnemyRingOut:'对手被撞飞出场！',
    copyShareText:'复制分享文本',
    shareCardPlayerTop:'玩家陀螺',
    shareCardEnemyTop:'敌方陀螺',
    shareCardChallengeRoad:'冠军之路',
    shareCardNode:'节点',
    shareCardOpenMatch:'自由对战',
    shareCardQuickBattle:'快速对战',
    shareCardVictory:'胜利',
    shareCardDefeat:'落败',
    cards:[
      {
        icon:'⚔',
        type:'强攻型',
        stats:'HP 85<br>SPIN 95<br>SPEED 14<br>MASS 1.2',
        skill:'⚔ 飞冲 · 沿直线猛扑目标。',
        pitch:'强势先手型陀螺，只要抓到第一道干净角度，就能顺势滚起节奏。',
        traits:['前段伤害高','擅长惩罚松散发射','逼住中圈时最强']
      },
      {
        icon:'🛡',
        type:'守御型',
        stats:'HP 120<br>SPIN 75<br>SPEED 10<br>MASS 1.5',
        skill:'🛡 堡垒脉冲 · 定住身位并把对手向外震开。',
        pitch:'重型控场选择，靠脉冲震退夺回空间并稳住中圈。',
        traits:['反突进能力强','最擅长回收中圈','重新定位偏慢']
      },
      {
        icon:'👾',
        type:'奇袭型',
        stats:'HP 70<br>SPIN 100<br>SPEED 16<br>MASS 0.9',
        skill:'👾 幻袭 · 提速切入并持续施压。',
        pitch:'依赖角度和漂移线生存的猎手型陀螺，最擅长边缘撕扯。',
        traits:['边线回收快','爆发节奏锋利','容错最低']
      },
      {
        icon:'✦',
        type:'强攻型',
        stats:'HP 78<br>SPIN 98<br>SPEED 15<br>MASS 1.1',
        skill:'✦ 飞冲 · 更快破线，但稳定性更低。',
        pitch:'更激进的冲击变体，一旦走到正面发射线就会立刻兑现伤害。',
        traits:['开局爆发更猛','追击速度更高','被拖慢后衰减明显']
      },
      {
        icon:'☄',
        type:'奇袭型',
        stats:'HP 66<br>SPIN 104<br>SPEED 17<br>MASS 0.8',
        skill:'☄ 幻袭 · 更锐利的边线猎杀与爆发节奏。',
        pitch:'为风险边墙而生的漂移掠食者，残局反扑尤其凶狠。',
        traits:['危险墙面表现最佳','残局压迫力极强','耐久最低']
      },
      {
        icon:'🜂',
        type:'强攻型',
        stats:'HP 92<br>SPIN 88<br>SPEED 13<br>MASS 1.3',
        skill:'🜂 飞冲 · 角度速度更稳，贴线咬合更强。',
        pitch:'稳控型冲击机体，擅长把正面对撞留在自己熟悉的中圈里。',
        traits:['发射窗口更宽','更能咬住碰撞','爆发节奏偏慢']
      },
      {
        icon:'✺',
        type:'强攻型',
        stats:'HP 74<br>SPIN 102<br>SPEED 17<br>MASS 0.9',
        skill:'✺ 飞冲 · 极高速突击，但燃尽窗口很短。',
        pitch:'玻璃大炮式冲击壳，只要线路够干净，就会在一瞬间完成兑现。',
        traits:['冲击起速最快','突击时间最短','非常吃发射角度']
      },
      {
        icon:'⛏',
        type:'强攻型',
        stats:'HP 98<br>SPIN 84<br>SPEED 12<br>MASS 1.4',
        skill:'⛏ 飞冲 · 重压式撞击，碰撞压迫维持更久。',
        pitch:'高密度冲击壳，用持续贴身压制换取更残暴的正面收益。',
        traits:['重碰撞压制强','打盾能力优秀','恢复节奏最慢']
      },
      {
        icon:'⛨',
        type:'守御型',
        stats:'HP 128<br>SPIN 72<br>SPEED 9<br>MASS 1.6',
        skill:'⛨ 堡垒脉冲 · 更深站桩，外震力更强。',
        pitch:'全壁垒防御机体，专门用来吃掉冲脸并一次次夺回中心。',
        traits:['脉冲最稳','反冲窗口最大','追击速度极低']
      },
      {
        icon:'⬡',
        type:'守御型',
        stats:'HP 104<br>SPIN 86<br>SPEED 12<br>MASS 1.2',
        skill:'⬡ 堡垒脉冲 · 更利落的反震节奏，回收更快。',
        pitch:'机动化装甲分支，能把防守顺势接成下一次抢中。',
        traits:['装甲里最均衡','回中速度快','站桩能力较低']
      },
      {
        icon:'🗿',
        type:'守御型',
        stats:'HP 136<br>SPIN 70<br>SPEED 8<br>MASS 1.7',
        skill:'🗿 堡垒脉冲 · 极重震波，自身锚定也最强。',
        pitch:'最大重量的控场机体，逼对手先撞上来再把节奏全部拿走。',
        traits:['纯硬度最高','击退最凶','追击最差']
      },
      {
        icon:'✧',
        type:'守御型',
        stats:'HP 98<br>SPIN 90<br>SPEED 13<br>MASS 1.1',
        skill:'✧ 堡垒脉冲 · 释放更灵活，滑出碰撞后能继续接线。',
        pitch:'镜面装甲壳能从坏接触里滑开，再立刻回身反震。',
        traits:['装甲里最灵活','重置更安全','纯阻停稍弱']
      },
      {
        icon:'☣',
        type:'奇袭型',
        stats:'HP 64<br>SPIN 106<br>SPEED 18<br>MASS 0.8',
        skill:'☣ 幻袭 · 带毒性的切侧漂移，会不断啃咬外线。',
        pitch:'像针一样的诡步分支，靠连续外线小咬口把局面拖进自己的节奏。',
        traits:['侧翼压迫持续','边线循环极快','专治犹豫']
      },
      {
        icon:'◎',
        type:'奇袭型',
        stats:'HP 76<br>SPIN 101<br>SPEED 15<br>MASS 0.9',
        skill:'◎ 幻袭 · 轨道阶段更长，贴墙回收更稳。',
        pitch:'偏控场的诡步机体，会绕更大的圈再选择更安全的回切线。',
        traits:['幻袭持续最长','场地重置能力强','爆发冲击偏弱']
      },
      {
        icon:'⌁',
        type:'奇袭型',
        stats:'HP 60<br>SPIN 108<br>SPEED 19<br>MASS 0.8',
        skill:'⌁ 幻袭 · 最激进的横切漂移，切线几乎无法预读。',
        pitch:'不稳定的偷局怪物，专门靠自己制造离谱角度来赢。',
        traits:['横漂断线最狠','最难被读懂','几乎没有容错']
      }
    ]
  };

  const textJa = {
    titleMain:'SPIN CLASH',
    titleSub:'アリーナ決戦',
    titleTagline:'短期決戦の高密度スピンデュエル。無駄な待ち時間も、サーバー依存もない。',
    titleProgressLabel:'進行状況',
    titleGoalLabel:'次の目標',
    titleQuickBattle:'クイックバトル',
    titleWorkshop:'ワークショップ',
    settingsTitle:'設定',
    backButton:'戻る',
    routeFromLabel:'遷移元',
    homeRoute:'ホーム',
    continuePath:'ロード再開',
    enterBattle:'ロード再開',
    loadoutTitle:'トップを選択',
    featuredTopTitle:'選択中のトップ',
    featuredTraitsTitle:'特性メモ',
    homeTopTitle:'現在のトップ',
    homeTopCountLabel:'解放済み',
    homeTopUnlocked:'解放済み',
    homeTopLocked:'未解放',
    topSourceStarter:'スターター',
    topSourceRoadReward:'ロード報酬',
    topSourceWorkshop:'SCRAP購入',
    topSourceRoadShop:'ロード報酬 / SCRAP購入',
    topUnlockRoadRank:'{rank} クリアで解放',
    topUnlockShopCost:'このカードを押して {cost} {currency} で購入',
    homeTopLockedSkill:'現在はシルエットのみ。能力詳細は解放後に表示される。',
    homeTopLockedHint:'解放すると素材感、輪郭、能力説明の全体が見えるようになる。',
    homeTopLockedHintRoad:'チャンピオンロードをさらに進めるとこのトップを解放できる。',
    homeTopLockedHintShop:'ロードアウト画面でこのトップカードを直接押すと、SCRAP が足りるときに購入できる。',
    homeTopLockedHintRoadShop:'このトップはロード報酬で解放するか、ロードアウト画面で SCRAP 購入できる。',
    topPurchaseConfirmKicker:'トップ解放',
    topPurchaseNeedMoreKicker:'SCRAP 不足',
    topPurchaseConfirmCopy:'今すぐ {cost} {currency} を使って {top} を解放する。確定すると現在のローカルセーブに恒久追加される。',
    topPurchaseEarnCopy:'{currency} が足りない。チャンピオンロードを進め、各試合報酬と初回クリア報酬を回収して残高を増やそう。',
    topPurchaseCostLine:'価格 {cost} {currency} · 現在 {balance} {currency}',
    topPurchaseShortfallLine:'価格 {cost} {currency} · あと {shortfall} {currency}',
    topPurchaseConfirmButton:'今すぐ買う',
    topPurchaseCancelButton:'まだやめる',
    topPurchaseCloseButton:'了解',
    titleBuildVersion:'Version 1.1.0',
    titleCopyright:'© 2026 Hakuro Kudo / Lumos',
    homeTopPrev:'<',
    homeTopNext:'>',
    homeTopEmpty:'解放済みトップを切り替えて強みを確認する。',
    quickBattleSubtitle:'クイックバトル',
    quickArenaTitle:'現在のアリーナ',
    quickArenaUnlocked:'解放済み',
    quickArenaLocked:'未解放',
    quickArenaDescriptions:{
      circle_bowl:'中央制圧の読みが最も素直に出る標準ボウル。',
      heart_bowl:'角度圧と外周判断を強く問うハートボウル。',
      hex_bowl:'反射が硬く、逃げ道が狭いヘックスボウル。',
      cyclone_bowl:'傾斜が強く、危険帯も早く始まる高速サークルボウル。',
      rose_bowl:'くびれたハート形が斜め射出と復帰判断を強く問う変形ボウル。',
      octa_bowl:'八面の返りが連鎖し、逃げ道がさらに短い多角ボウル。'
    },
    quickTopTitle:'出撃トップ',
    quickTopLocked:'未解放',
    quickTopReady:'出撃可能',
    quickTopOwnedStarterHint:'開始時から使用可能',
    quickTopOwnedRoadHint:'ロード報酬を獲得済み',
    quickTopOwnedShopHint:'SCRAP解放済み',
    quickTopOwnedReadyHint:'すぐ出撃できる',
    quickTopPathAction:'ロードへ向かう',
    quickTopEarnAction:'SCRAPを稼ぐ',
    quickTopWalletNeedLine:'現在 {balance} {currency} · 価格 {cost} {currency}',
    quickTopWalletOwnedLine:'所持 {balance} {currency}',
    quickTopLockedHint:'未解放のトップではクイックバトルに入れない。',
    homeRouteLockedHint:'現在プレビュー中のトップは未解放。解放済みトップへ戻してから対戦ルートへ入る必要がある。',
    quickStartBlockedHint:'現在のトップは未解放。ホームに戻って解放済みトップへ切り替える必要がある。',
    quickStartBlockedButton:'出撃不可',
    quickStartReadyHint:'アリーナ準備完了。すぐ開始できる。',
    quickStartArenaLockedHint:'このアリーナは未解放。開始時に解放またはトライアルを試みる。',
    quickStartArenaUnlockButton:'解放して開始',
    quickStartArenaUnlockHint:'{cost} SCRAP を使ってこのアリーナを解放し、そのまま対戦を始める。',
    quickStartArenaTrialButton:'広告でトライアル',
    quickStartArenaTrialHint:'SCRAP が不足しているため、広告視聴でこのアリーナのセッショントライアルを開始する。',
    challengeSubtitle:'チャンピオンロード',
    arenaOptions:['蒼輪闘庭','緋心曲域','断稜角陣','嵐渦深淵','棘華幽阱','八鏡回廊'],
    fightButton:'対戦開始',
    challengeButton:'ロード開始',
    roundNext:'次のラウンドがまもなく始まる',
    replay:'もう一戦',
    nextNode:'次のノード',
    retryNode:'ノード再挑戦',
    roadClear:'ロード制覇',
    rematch:'トップ変更',
    rewardDouble:'報酬2倍',
    rewardClaimed:'2倍獲得済み',
    rewardContinue:'コンティニュー +広告',
    rewardBusy:'リクエストは送信済み。少し待ってください。',
    rewardLoading:'まだ読み込み中。少し待ってからもう一度。',
    rewardUnavailable:'今はこの内容を利用できない。',
    rewardDeclined:'今回は有効にならなかった。',
    rewardError:'今回はうまくいかなかった。少し待ってからもう一度。',
    rewardDoubleBusy:'報酬2倍のリクエストは送信済み。少し待ってください。',
    rewardDoubleLoading:'報酬2倍を読み込み中。少し待ってからもう一度。',
    rewardDoubleUnavailable:'今回は報酬2倍を受け取れなかった。基本報酬はそのまま入り、次の試合でまた試せる。',
    rewardDoubleDeclined:'今回は報酬2倍が有効にならなかった。もう一度押せば再試行できる。',
    rewardDoubleError:'今回は報酬2倍を受け取れなかった。基本報酬はそのまま入り、次の試合でまた試せる。',
    rewardContinueBusy:'この挑戦を続けるリクエストは送信済み。少し待ってください。',
    rewardContinueLoading:'この挑戦を続ける準備中。少し待ってからもう一度。',
    rewardContinueUnavailable:'今回はこの挑戦を続けられなかった。この試合はここで終了するが、報酬は受け取れ、次の挑戦でまた試せる。',
    rewardContinueDeclined:'今回はこの挑戦を続けられなかった。もう一度押せば再試行できる。',
    rewardContinueError:'今回はこの挑戦を続けられなかった。この試合はここで終了するが、報酬は受け取れ、次の挑戦でまた試せる。',
    rewardTrialBusy:'アリーナトライアルのリクエストは送信済み。少し待ってください。',
    rewardTrialLoading:'アリーナトライアルを読み込み中。少し待ってからもう一度。',
    rewardTrialUnavailable:'今回はアリーナトライアルを開始できなかった。後でもう一度試すか、別のアリーナを選んでください。',
    rewardTrialDeclined:'今回はアリーナトライアルを開始できなかった。もう一度押せば再試行できる。',
    rewardTrialError:'今回はアリーナトライアルを開始できなかった。後でもう一度試すか、別のアリーナを選んでください。',
    shareResult:'結果をシェア',
    resultBreakdownBase:'基本',
    resultBreakdownNode:'ノード',
    resultBreakdownFirstClear:'初回突破',
    resultBreakdownRank:'ランク補正',
    resultNextNodeLabel:'次',
    resultRetryLabel:'再挑戦',
    resultRoadLabel:'ロード',
    resultArenaLabel:'アリーナ',
    resultNodeLabel:'ノード',
    resultReasonLabel:'決着',
    resultShareLabel:'共有モーメント',
    resultRewardLabel:'報酬',
    resultReturnToPath:'ロードへ戻る',
    resultReturnToQuick:'クイックへ戻る',
    resultReturnToHome:'ホームへ戻る',
    resultAdjustPath:'ロードで調整',
    resultAdjustQuick:'クイックで調整',
    resultAdjustHome:'トップ変更',
    quickMode:'クイックバトル',
    challengeMode:'チャンピオンロード',
    workshopToggle:'ワークショップを開く',
    workshopClose:'ワークショップを閉じる',
    workshopTitle:'ワークショップ研究',
    workshopHint:'SCRAP を使って恒久研究を強化する。',
    workshopBuy:'強化',
    workshopMaxed:'最大',
    workshopLocked:'SCRAP 不足',
    workshopUnlocked:'研究を強化した',
    workshopLevel:'LV',
    workshopCurrent:'現在',
    workshopNext:'次',
    settingsHint:'言語と音声トグルは即時反映され、現在のローカルセーブに保存される。',
    settingsLanguageLabel:'言語',
    settingsMusicLabel:'音楽',
    settingsSfxLabel:'効果音',
    settingsToggleOn:'ON',
    settingsToggleOff:'OFF',
    settingsMusicOn:'音楽: ON',
    settingsMusicOff:'音楽: OFF',
    settingsSfxOn:'効果音: ON',
    settingsSfxOff:'効果音: OFF',
    roadRankTitle:'ロードランク',
    roadRankLocked:'未解放',
    roadRankUnlocked:'解放済み',
    roadRankHint:'現在の大会強度と報酬帯。',
    roadRankRewardLabel:'報酬',
    roadRankRewardTopLabel:'報酬トップ',
    challengeCurrentTopTitle:'現在の出撃トップ',
    challengeArenaInfo:'アリーナ {value}',
    challengeEnemyInfo:'相手 {value}',
    challengeRuleInfo:'ルール {value}',
    challengeRewardInfo:'報酬 {value}',
    challengeFirstClearInfo:'初回 +{value}',
    challengeRankInfo:'{rank} x{multiplier}',
    challengeCheckpointInfo:'突破でチェックポイント保存',
    challengeLocked:'次の対戦を解放するには現在のノードを突破する必要がある。',
    challengeComplete:'ロード制覇済み。繰り返し挑戦して報酬を伸ばせる。',
    challengeFail:'挑戦失敗。1回だけコンティニューするか、ノードを再挑戦できる。',
    challengeContinueUsed:'このノードではコンティニュー済み。',
    unlockArena:'解放',
    unlockTop:'トップ解放',
    unlockTopReward:'ロード報酬を解放',
    trialArena:'トライアル中',
    lockedArena:'未解放',
    lockedTop:'未解放',
    playerRole:'YOU',
    enemyRole:'CPU',
    statusReady:'READY',
    statusGuarding:'GUARD',
    statusIntentSkill:'SKILL',
    statusIntentDash:'DASH',
    statusIntentGuard:'GUARD',
    hp:'HP',
    spin:'SPIN',
    burst:'BURST',
    dashName:'ダッシュ',
    dashIcon:'⚡',
    guardName:'ガード',
    guardIcon:'🛡',
    swapIcon:'⇄',
    swapLabel:'切替',
    loadoutHintQuick:'単発対戦のアリーナを選ぶ。現在のトップはホームで決定される。',
    loadoutHintChallenge:'固定ノードを連戦し、モディファイアと持続報酬で進行を押し上げる。',
    storageNoticeSession:'保存モード：このセッションのみ。新しいタブでは進行が残らない場合がある。',
    storageNoticeWindowName:'保存モード：このタブのみ。新しいウィンドウでは進行が残らない場合がある。',
    storageNoticeMemory:'保存モード：一時メモリのみ。再読み込みで進行は失われる。',
    shareTitle:'Spin Clash',
    sharePrefix:'Spin Clash リザルト',
    shareMoments:{
      road_clear:'ロード制覇',
      challenge_clear:'ノード突破',
      ring_out:'リングアウト',
      perfect_win:'完勝',
      close_loss:'惜敗',
      victory:'勝利',
      defeat:'敗北'
    },
    shareTemplates:{
      road_clear:'{title}：{top} で {arena} を制し、チャンピオンロードを完走した。',
      challenge_clear:'{title}：{top} で {arena} のノード {node} を突破した。',
      ring_out:'{title}：{top} で {arena} のリングアウト勝ちを決めた。',
      perfect_win:'{title}：{top} で {arena} を {scorePlayer}-{scoreEnemy} で完勝した。',
      close_loss:'{title}：{arena} で {scorePlayer}-{scoreEnemy} の惜敗。次は取り返す。',
      victory:'{title}：{top} で {arena} を制した。',
      defeat:'{title}：{top} で {arena} を戦い抜いた。'
    },
    currencyLabel:'SCRAP',
    walletLabel:'残高',
    localeButtons:{
      en:'EN',
      zh:'中文',
      ja:'日本語'
    },
    hintAim:'ドラッグで狙い、離して発射。',
    hintActive:'SPACE でダッシュ | E でガード | Q でバーストスキル。',
    hintSkillReady:'Q 準備完了',
    roundLabel:'ROUND',
    roundWinPlayer:'YOU WIN!',
    roundWinEnemy:'ENEMY WINS',
    roundWinDraw:'DRAW',
    roundReasonRingOut:'リングアウト',
    roundReasonSpinOut:'スピン切れ',
    roundReasonHpBreak:'HP ブレイク',
    roundReasonTimeUp:'タイムアップ - HP 判定',
    fightCallout:'FIGHT!',
    nodeLocked:'ノードはまだ解放されていない。',
    checkpointLabel:'チェックポイント',
    tierBoss:'ボス',
    tierFinal:'最終戦',
    resumeLabel:'再開地点',
    noBonus:'ボーナスなし',
    battleIntroQuickStage:'クイックバトル',
    battleIntroNodeLabel:'NODE',
    battleIntroVersus:' VS ',
    skillLabels:{
      'Fly Charge':'フライチャージ',
      'Fortress Pulse':'フォートレスパルス',
      'Phantom':'ファントム'
    },
    skillMessages:{
      player:{
        'Fly Charge':'フライチャージ！',
        'Fortress Pulse':'フォートレスパルス！',
        'Phantom':'ファントム！'
      },
      enemy:{
        'Fly Charge':'敵がフライチャージを使った！',
        'Fortress Pulse':'敵がフォートレスパルスを使った！',
        'Phantom':'敵がファントムを使った！'
      }
    },
    messageDash:'ダッシュ！',
    messageGuard:'ガード！',
    messageBurstOrb:'+55 BURST',
    messageHeavyCollision:'強烈衝突！',
    messageSuperImpact:'超高衝撃!!',
    messagePlayerRingOut:'場外へ弾き出された！',
    messageEnemyRingOut:'相手が場外へ吹き飛んだ！',
    copyShareText:'共有テキストをコピー',
    shareCardPlayerTop:'PLAYER TOP',
    shareCardEnemyTop:'ENEMY TOP',
    shareCardChallengeRoad:'チャンピオンロード',
    shareCardNode:'NODE',
    shareCardOpenMatch:'オープンマッチ',
    shareCardQuickBattle:'クイックバトル',
    shareCardVictory:'VICTORY',
    shareCardDefeat:'DEFEAT',
    cards:[
      {
        icon:'⚔',
        type:'強攻型',
        stats:'HP 85<br>SPIN 95<br>SPEED 14<br>MASS 1.2',
        skill:'⚔ フライチャージ · 標的へ一直線に突っ込む。',
        pitch:'最初のきれいな角度をそのまま主導権に変える、強烈な先手型トップ。',
        traits:['序盤火力が高い','甘い発射を咎めやすい','中央接触を押し付けると強い']
      },
      {
        icon:'🛡',
        type:'守御型',
        stats:'HP 120<br>SPIN 75<br>SPEED 10<br>MASS 1.5',
        skill:'🛡 フォートレスパルス · 位置を固めて相手を外へ弾く。',
        pitch:'重厚な制圧型で、衝撃波によって中央を取り返し続ける。',
        traits:['突進迎撃が強い','中央の奪還が得意','立て直しは遅め']
      },
      {
        icon:'👾',
        type:'奇襲型',
        stats:'HP 70<br>SPIN 100<br>SPEED 16<br>MASS 0.9',
        skill:'👾 ファントム · 加速しながら圧をかけ続ける。',
        pitch:'角度とドリフトラインを頼りに生きる、外周圧が鋭いハンター型。',
        traits:['外周からの立て直しが速い','バースト展開が鋭い','ミス許容が低い']
      },
      {
        icon:'✦',
        type:'強攻型',
        stats:'HP 78<br>SPIN 98<br>SPEED 15<br>MASS 1.1',
        skill:'✦ フライチャージ · 破線速度は高いが安定性は低い。',
        pitch:'正面の発射線を掴んだ瞬間に成果へ変える、さらに攻撃的な派生型。',
        traits:['開幕が爆発的','追撃速度が高い','止められると失速しやすい']
      },
      {
        icon:'☄',
        type:'奇襲型',
        stats:'HP 66<br>SPIN 104<br>SPEED 17<br>MASS 0.8',
        skill:'☄ ファントム · さらに鋭い外周狩りとバースト展開。',
        pitch:'危険な壁際を獲物に変える、終盤の切り返しが凶悪なドリフト捕食者。',
        traits:['危険な壁面で最強','逆転圧が非常に高い','耐久は最も低い']
      },
      {
        icon:'🜂',
        type:'強攻型',
        stats:'HP 92<br>SPIN 88<br>SPEED 13<br>MASS 1.3',
        skill:'🜂 フライチャージ · 角度速度を抑え、ライン保持を強める。',
        pitch:'安定した衝撃フレームで、正面接触を自分の中央戦へ固定しやすい。',
        traits:['発射許容が広い','接触維持が長い','バースト速度は遅め']
      },
      {
        icon:'✺',
        type:'強攻型',
        stats:'HP 74<br>SPIN 102<br>SPEED 17<br>MASS 0.9',
        skill:'✺ フライチャージ · 超高速の一撃だが、燃え尽きまでが短い。',
        pitch:'一度のきれいな侵入で成果を奪う、ガラス砲寄りの衝撃シェル。',
        traits:['衝撃の初速が最速','突進時間が最短','角度精度が必須']
      },
      {
        icon:'⛏',
        type:'強攻型',
        stats:'HP 98<br>SPIN 84<br>SPEED 12<br>MASS 1.4',
        skill:'⛏ フライチャージ · 重い叩き付けで接触圧を長く残す。',
        pitch:'高密度な衝撃シェルで、テンポを落としてでも正面の継続圧を取る。',
        traits:['重接触が強い','ガード破り向き','立て直しは最遅']
      },
      {
        icon:'⛨',
        type:'守御型',
        stats:'HP 128<br>SPIN 72<br>SPEED 9<br>MASS 1.6',
        skill:'⛨ フォートレスパルス · 深く踏ん張り、外への押し出しを強める。',
        pitch:'全面防壁の守備機で、突進を受け止めて中央を取り返し続ける。',
        traits:['パルス安定度最大','迎撃窓が広い','追撃速度は極低']
      },
      {
        icon:'⬡',
        type:'守御型',
        stats:'HP 104<br>SPIN 86<br>SPEED 12<br>MASS 1.2',
        skill:'⬡ フォートレスパルス · 切り返しが軽く、再進入も速い。',
        pitch:'機動寄りの装甲派生で、防御からそのまま中央奪還へつなげやすい。',
        traits:['装甲内で最も均衡','中央へ戻るのが速い','停滞力はやや低い']
      },
      {
        icon:'🗿',
        type:'守御型',
        stats:'HP 136<br>SPIN 70<br>SPEED 8<br>MASS 1.7',
        skill:'🗿 フォートレスパルス · 最大級の衝撃波と自己固定力。',
        pitch:'重量最大の制圧機体で、相手に先にぶつからせてから全部を奪い返す。',
        traits:['純粋な硬さが最大','吹き飛ばし最強','追撃性能は最低']
      },
      {
        icon:'✧',
        type:'守御型',
        stats:'HP 98<br>SPIN 90<br>SPEED 13<br>MASS 1.1',
        skill:'✧ フォートレスパルス · 柔らかく受け流し、返しの滑りも残す。',
        pitch:'鏡面装甲で悪い接触から滑り抜け、すぐに反撃へ転じる。',
        traits:['装甲で最も軽快','仕切り直しが安全','停止力は控えめ']
      },
      {
        icon:'☣',
        type:'奇襲型',
        stats:'HP 64<br>SPIN 106<br>SPEED 18<br>MASS 0.8',
        skill:'☣ ファントム · 側面を噛み続ける毒のようなドリフト。',
        pitch:'針のような奇策派生で、何度も外周を削って相手のテンポを壊す。',
        traits:['側圧が止まらない','外周ループが非常に速い','迷いを咎める']
      },
      {
        icon:'◎',
        type:'奇襲型',
        stats:'HP 76<br>SPIN 101<br>SPEED 15<br>MASS 0.9',
        skill:'◎ ファントム · 周回時間が長く、壁際リセットが安定する。',
        pitch:'やや制圧寄りの奇策シェルで、大きく回ってから安全な戻り線を選ぶ。',
        traits:['ファントム時間が最長','場面の作り直しが得意','瞬間火力は弱め']
      },
      {
        icon:'⌁',
        type:'奇襲型',
        stats:'HP 60<br>SPIN 108<br>SPEED 19<br>MASS 0.8',
        skill:'⌁ ファントム · 横切りが最も鋭く、軌道が読まれにくい。',
        pitch:'自分で不条理な角度を作って勝つ、不安定な盗み勝ち特化機。',
        traits:['横漂いが最凶','読みづらさ最大','許容ミスはゼロに近い']
      }
    ]
  };

  root.config.textLocales = {
    en:textEn,
    zh:textZh,
    ja:textJa
  };

  root.config.text = cloneLocale(textEn);

  root.config.contentLocales = {
    zh:{
      arenas:{
        circle_bowl:{ label:'苍轮斗庭' },
        heart_bowl:{ label:'绯心曲域' },
        hex_bowl:{ label:'断棱角阵' },
        cyclone_bowl:{ label:'岚涡深渊' },
        rose_bowl:{ label:'棘华幽阱' },
        octa_bowl:{ label:'八镜回廊' }
      },
      tops:{
        impact:{ name:'赤霄锋' },
        armor:{ name:'苍甲垣' },
        trick:{ name:'夜岚游锋' },
        impact_breaker:{ name:'破军断戟' },
        trick_raider:{ name:'逐影袭星' },
        impact_vanguard:{ name:'镇岳冲角' },
        impact_nova:{ name:'星陨流焰' },
        impact_tremor:{ name:'撼岳重锋' },
        armor_bastion:{ name:'不动天城' },
        armor_aegis:{ name:'光轮御壁' },
        armor_mammoth:{ name:'磐象镇阙' },
        armor_mirror:{ name:'镜轮返界' },
        trick_venom:{ name:'碧牙蚀月' },
        trick_orbit:{ name:'回天环轨' },
        trick_glitch:{ name:'狐火断界' }
      },
      research:{
        spin_core:{
          label:'旋转核心',
          description:'提高所有陀螺的最大转力储备。',
          statLabel:'最大 SPIN',
          levels:[
            { preview:'最大 SPIN +4%' },
            { preview:'最大 SPIN +8%' },
            { preview:'最大 SPIN +12%' },
            { preview:'最大 SPIN +16%' }
          ]
        },
        guard_frame:{
          label:'护框结构',
          description:'强化外环结构，让你更稳地扛住碰撞。',
          statLabel:'最大 HP',
          levels:[
            { preview:'最大 HP +3%' },
            { preview:'最大 HP +6%' },
            { preview:'最大 HP +9%' },
            { preview:'最大 HP +12%' }
          ]
        },
        burst_relay:{
          label:'爆发中继',
          description:'提高爆发积累速度，让技能更早上线。',
          statLabel:'爆发积累',
          levels:[
            { preview:'爆发积累 +5%' },
            { preview:'爆发积累 +10%' },
            { preview:'爆发积累 +15%' },
            { preview:'爆发积累 +20%' }
          ]
        }
      },
      roadRanks:{
        rank_i:{ label:'RANK I', description:'基础赛事调校与标准奖励。' },
        rank_ii:{ label:'RANK II', description:'敌方调校更锋利，但 SCRAP 奖励加成仍保持克制。' },
        rank_iii:{ label:'RANK III', description:'最终征途压力更高，敌方爬升更强，但不会变成失控刷钱档。' }
      },
      enemyPresets:{
        armor_standard:{ label:'装甲锚点' },
        trick_standard:{ label:'诡步猎手' },
        impact_standard:{ label:'冲击重拳' },
        armor_ram:{ label:'装甲冲槌' },
        trick_drifter:{ label:'诡步漂移' },
        impact_blitz:{ label:'冲击闪击' },
        armor_bastion:{ label:'装甲堡垒' },
        trick_duelist:{ label:'诡步决斗手' },
        impact_reaper:{ label:'冲击收割者' }
      },
      modifiers:{
        standard:{ label:'标准', description:'没有额外规则。' },
        overclock:{ label:'超频', description:'双方都以更高的爆发积累开局。' },
        ironwall:{ label:'铁壁', description:'敌方耐久获得强化。' },
        sudden_death:{ label:'骤死', description:'耐久更低，回合更快。' },
        burst_rush:{ label:'爆发猛冲', description:'玩家以更接近爆发技能的状态起手。' },
        heavy_floor:{ label:'重压地板', description:'更重的地面阻力会奖励控场。' },
        launch_surge:{ label:'起步过载', description:'双方一开局就拥有更快的爆发压力。' },
        grind_core:{ label:'碾压核心', description:'更重的脚感让对局变成控场拉锯。' },
        low_spin:{ label:'低转储备', description:'更低的转力储备会放大每一次失误。' }
      },
      challengeRoad:{
        'node-1':{ name:'开场定序', chapterLabel:'预选阶段', previewLabel:'开场定序', previewDesc:'一场基准对决，先让玩家重新找回稳控中圈的感觉。' },
        'node-2':{ name:'心形切入', chapterLabel:'预选阶段', previewLabel:'心形切入', previewDesc:'心形碗场里的角度压迫，会惩罚每一次草率发射。' },
        'node-3':{ name:'红线关口', chapterLabel:'预选阶段', previewLabel:'章节首领', previewDesc:'第一场检查点对决。爆发节奏更快，正面碰撞压力更强。' },
        'node-4':{ name:'破甲试炼', chapterLabel:'场地巡回', previewLabel:'解锁战', previewDesc:'更硬的装甲变体会借心形碗场逼你做出更重的走线承诺。' },
        'node-5':{ name:'紧迫时限', chapterLabel:'场地巡回', previewLabel:'六角漂移', previewDesc:'漂移型诡步预设加上更低转储备，会严惩凌乱的贴墙脱出。' },
        'node-6':{ name:'压地强攻', chapterLabel:'场地巡回', previewLabel:'检查点首领', previewDesc:'第二场检查点对决。更快的爆发压力，会把六角碗场变成一场短跑战。' },
        'node-7':{ name:'争夺中圈', chapterLabel:'宿敌连战', previewLabel:'锁定中圈', previewDesc:'堡垒型装甲预设加上更重的脚感，会逼你先赢下圆形碗场中心，再谈后续节奏。' },
        'node-8':{ name:'破线复仇', chapterLabel:'宿敌连战', previewLabel:'刀锋对决', previewDesc:'骤死规则下对上全压型诡步决斗手，任何一次糟糕发射都会立刻付出代价。' },
        'node-9':{ name:'半决强碰', chapterLabel:'冠军决赛', previewLabel:'半决赛', previewDesc:'半决赛会变成一场残酷的冲击追猎，只要贴地失误就会被立刻连段惩罚。' },
        'node-10':{ name:'王冠决战', chapterLabel:'冠军决赛', previewLabel:'决赛', previewDesc:'最终冠军战。节奏更快、路线更险，没有任何安全余量。' }
      }
    },
    ja:{
      arenas:{
        circle_bowl:{ label:'蒼輪闘庭', reading:'そうりんとうてい' },
        heart_bowl:{ label:'緋心曲域', reading:'ひしんきょくいき' },
        hex_bowl:{ label:'断稜角陣', reading:'だんりょうかくじん' },
        cyclone_bowl:{ label:'嵐渦深淵', reading:'らんかしんえん' },
        rose_bowl:{ label:'棘華幽檻', reading:'きょくかゆうかん' },
        octa_bowl:{ label:'八鏡回廊', reading:'はっきょうかいろう' }
      },
      tops:{
        impact:{ name:'赤霄鋒', reading:'せきしょうほう' },
        armor:{ name:'蒼甲垣', reading:'そうこうえん' },
        trick:{ name:'夜嵐遊鋒', reading:'やらんゆうほう' },
        impact_breaker:{ name:'破軍断戟', reading:'はぐんだんげき' },
        trick_raider:{ name:'逐影襲星', reading:'ちくえいしゅうせい' },
        impact_vanguard:{ name:'鎮岳衝角', reading:'ちんがくしょうかく' },
        impact_nova:{ name:'星隕流焔', reading:'せいいんりゅうえん' },
        impact_tremor:{ name:'撼岳重鋒', reading:'かんがくじゅうほう' },
        armor_bastion:{ name:'不動天城', reading:'ふどうあまぎ' },
        armor_aegis:{ name:'光輪御壁', reading:'こうりんごへき' },
        armor_mammoth:{ name:'磐象鎮塁', reading:'ばんしょうちんるい' },
        armor_mirror:{ name:'鏡輪返界', reading:'きょうりんへんかい' },
        trick_venom:{ name:'碧牙蝕月', reading:'へきがしょくげつ' },
        trick_orbit:{ name:'回天環軌', reading:'かいてんかんき' },
        trick_glitch:{ name:'狐火断界', reading:'きつねびだんかい' }
      },
      research:{
        spin_core:{
          label:'スピンコア',
          description:'すべてのトップの最大スピン備蓄を引き上げる。',
          statLabel:'最大 SPIN',
          levels:[
            { preview:'最大 SPIN +4%' },
            { preview:'最大 SPIN +8%' },
            { preview:'最大 SPIN +12%' },
            { preview:'最大 SPIN +16%' }
          ]
        },
        guard_frame:{
          label:'ガードフレーム',
          description:'外周フレームを補強し、被弾後の踏ん張りを安定させる。',
          statLabel:'最大 HP',
          levels:[
            { preview:'最大 HP +3%' },
            { preview:'最大 HP +6%' },
            { preview:'最大 HP +9%' },
            { preview:'最大 HP +12%' }
          ]
        },
        burst_relay:{
          label:'バーストリレー',
          description:'バースト蓄積を速め、スキルの立ち上がりを早める。',
          statLabel:'BURST 蓄積',
          levels:[
            { preview:'BURST 蓄積 +5%' },
            { preview:'BURST 蓄積 +10%' },
            { preview:'BURST 蓄積 +15%' },
            { preview:'BURST 蓄積 +20%' }
          ]
        }
      },
      roadRanks:{
        rank_i:{ label:'RANK I', description:'基本の大会調整と標準報酬。' },
        rank_ii:{ label:'RANK II', description:'敵の調整は鋭くなるが、SCRAP ボーナスは抑制されたまま。' },
        rank_iii:{ label:'RANK III', description:'最終ロード級の圧力と敵成長がかかるが、報酬効率は暴走させない。' }
      },
      enemyPresets:{
        armor_standard:{ label:'アーマーアンカー' },
        trick_standard:{ label:'トリックハンター' },
        impact_standard:{ label:'インパクトブルーザー' },
        armor_ram:{ label:'アーマーラム' },
        trick_drifter:{ label:'トリックドリフター' },
        impact_blitz:{ label:'インパクトブリッツ' },
        armor_bastion:{ label:'アーマーバスティオン' },
        trick_duelist:{ label:'トリックデュエリスト' },
        impact_reaper:{ label:'インパクトリーパー' }
      },
      modifiers:{
        standard:{ label:'スタンダード', description:'特別なルールなし。' },
        overclock:{ label:'オーバークロック', description:'両者とも高いバースト蓄積で開始する。' },
        ironwall:{ label:'アイアンウォール', description:'敵の耐久が強化される。' },
        sudden_death:{ label:'サドンデス', description:'HP が低く、ラウンド進行が速い。' },
        burst_rush:{ label:'バーストラッシュ', description:'プレイヤーはバーストスキルに近い状態で開幕する。' },
        heavy_floor:{ label:'ヘビーフロア', description:'重い床摩擦がコントロールを報いる。' },
        launch_surge:{ label:'ローンチサージ', description:'両者とも序盤から高いバースト圧を持つ。' },
        grind_core:{ label:'グラインドコア', description:'重い足回りが試合をコントロールの削り合いに変える。' },
        low_spin:{ label:'ロースピン', description:'少ないスピン備蓄が一つひとつのミスを重くする。' }
      },
      challengeRoad:{
        'node-1':{ name:'開幕シード', chapterLabel:'予選', previewLabel:'開幕シード', previewDesc:'まずは基準戦。安定して中央を取る感覚を取り戻す。' },
        'node-2':{ name:'ハートカット', chapterLabel:'予選', previewLabel:'ハートカット', previewDesc:'ハートボウルでの角度圧が、雑な発射を容赦なく咎める。' },
        'node-3':{ name:'レッドラインゲート', chapterLabel:'予選', previewLabel:'チャプターボス', previewDesc:'最初のチェックポイント戦。高いバースト速度と正面衝突が主役。' },
        'node-4':{ name:'ガードブレイク', chapterLabel:'アリーナサーキット', previewLabel:'アンロック戦', previewDesc:'さらに硬いアーマー派生が、ハートボウルで重いライン選択を迫る。' },
        'node-5':{ name:'タイトクロック', chapterLabel:'アリーナサーキット', previewLabel:'ヘックスドリフト', previewDesc:'ドリフト型トリックと低スピン備蓄が、壁際の雑な離脱を罰する。' },
        'node-6':{ name:'フロアプレス', chapterLabel:'アリーナサーキット', previewLabel:'チェックポイントボス', previewDesc:'二つ目のチェックポイント戦。速いバースト圧がヘックスボウルを短距離戦に変える。' },
        'node-7':{ name:'センタークレーム', chapterLabel:'ライバルシリーズ', previewLabel:'センターロック', previewDesc:'要塞型アーマーと重い足回りが、まず中央を奪い切れるかを厳しく問う。' },
        'node-8':{ name:'ブレイクライン', chapterLabel:'ライバルシリーズ', previewLabel:'ナイフエッジ', previewDesc:'サドンデス下で全振りのトリックデュエリストと再戦。雑な発射は即座に致命傷になる。' },
        'node-9':{ name:'セミクラッシュ', chapterLabel:'チャンピオンシップ', previewLabel:'準決勝', previewDesc:'準決勝は苛烈なインパクト追撃戦へ変わり、地上での小さなミスがそのまま被弾ルートになる。' },
        'node-10':{ name:'クラウンクラッシュ', chapterLabel:'チャンピオンシップ', previewLabel:'ファイナル', previewDesc:'最終決戦。テンポは速く、ルートは不安定で、逃げ場はない。' }
      }
    }
  };
})();
